### ISSUE TITLE
Error initializing user local eclipse configuration

### ISSUE THREAD

**Issue by evancarey** [ervandew/eclim#117]
Hi All,

I hope this is the place to ask this...  I'm trying to install eclim and I'm getting this error when selecting a "User Local Eclipse Location" from the Eclim Installer dialog:

Error initializing user local eclipse configuration.
java.lang.RuntimeException: Could not find the eclipse launcher jar for path:
at org.eclim.installer.step.EclipseStep$InitializeAction$1.run(EclipseStep.java:436)
at foxtrot.AbstractWorkerThread$1.run(AbstractWorkerThread.java:40)
at java.security.AccessController.doPrivileged(Native Method)
at foxtrot.AbstractWorkerThread.runTask(AbstractWorkerThread.java:36)
at foxtrot.workers.SingleWorkerThread.run(SingleWorkerThread.java:199)
at foxtrot.workers.SingleWorkerThread.run(SingleWorkerThread.java:182)
at java.lang.Thread.run(Thread.java:680)

I'm on a mac (v10.6.8) and I have multiple installations of Eclipse (Indigo).  I'm selecting an Eclipse installation that is also STS (v2.8.1).

Any guidance would be appreciated.

Thanks,
Evan

**Comment by sideshowbarker** [comment]
Yeah for the record here, you need to give eclim the path to the `Eclipse.app/Contents/Eclipse` subdirectory in whatever directory you’ve installed Eclipse in. See https://github.com/ervandew/eclim/issues/436#issuecomment-146031012 and other comments in that thread.
