### ISSUE TITLE
I can't connect gvim to the eclipse, the server is on.

### ISSUE THREAD

**Issue by ColorFuzzy** [ervandew/eclim#126]
eclipse 3.7.2
eclim 1.7.5
jre-7u4-windows-i586-iftw

Situation one
open the server, then open gvim, wihtout open eclipse
:PingEclim
I get bellow:
    java.lang.RuntimeException: No command 'ping' found.
    while executing command (port: 9091): -edtior vim -command ping

then-close all

Situation two
open eclipse, choose a file and open it with vim inside vim
sometimes I open it inside eclipse successfull, but sometimes it opens the file outside eclipse in gvim
I get bellow:

2012-06-08 02:42:30,547 INFO  [org.eclim.eclipse.AbstractEclimApplication] Workspace: E:/Dropbox/Work/python/code/eclipse
2012-06-08 02:42:30,550 INFO  [org.eclim.eclipse.AbstractEclimApplication] Starting eclim...
2012-06-08 02:42:30,570 INFO  [org.eclim.eclipse.AbstractEclimApplication] Loading plugin org.eclim
2012-06-08 02:42:30,645 INFO  [org.eclim.eclipse.AbstractEclimApplication] Loading plugin org.eclim.core
2012-06-08 02:42:30,782 INFO  [org.eclim.plugin.core.CorePlugin] Loading eclim plugins...
2012-06-08 02:42:30,785 INFO  [org.eclim.plugin.core.CorePlugin] Plugins loaded.
2012-06-08 02:42:30,786 INFO  [org.eclim.eclipse.AbstractEclimApplication] Loaded plugin org.eclim.core
2012-06-08 02:42:30,786 INFO  [org.eclim.eclipse.AbstractEclimApplication] Eclim Server Started on: 127.0.0.1:9091
2012-06-08 02:42:30,791 ERROR [org.eclim.eclipse.AbstractEclimApplication] Error starting eclim:
java.lang.RuntimeException: java.net.BindException: Address already in use: JVM_Bind
    at com.martiansoftware.nailgun.NGServer.run(NGServer.java:426)
    at org.eclim.eclipse.AbstractEclimApplication.start(AbstractEclimApplication.java:139)
    at org.eclim.eclipse.headed.EclimdView$EclimThread.run(EclimdView.java:126)
Caused by: java.net.BindException: Address already in use: JVM_Bind
    at java.net.DualStackPlainSocketImpl.bind0(Native Method)
    at java.net.DualStackPlainSocketImpl.socketBind(Unknown Source)
    at java.net.AbstractPlainSocketImpl.bind(Unknown Source)
    at java.net.PlainSocketImpl.bind(Unknown Source)
    at java.net.ServerSocket.bind(Unknown Source)
    at java.net.ServerSocket.<init>(Unknown Source)
    at com.martiansoftware.nailgun.NGServer.run(NGServer.java:408)
    ... 2 more

then open gvim still with eclipse on
:PingEclim
I get bellow:
    java.lang.RuntimeException: No command 'ping' found.
    while executing command (port: 9091): -edtior vim -command ping

**Comment by casank25** [comment]
@MusicalNeutrino  +1
