### ISSUE TITLE
Eclipse indigo + eclim 1.7.6 + Ubuntu 12.0.4 GUI installer problem

### ISSUE THREAD

**Issue by vermest** [ervandew/eclim#129]
Hi,

Installation fails.
I have stock eclipse, with minor set of plugins (findbugs, pmd, checkstyle,sts).
This is what I got:
2012-06-09 15:30:28,207 INFO  [org.formic.util.CommandExecutor] java -Xmx256M -jar /home/vermes/eclipse-new/plugins/org.eclipse.equinox.launcher_1.2.0.v20110502.jar -clean -application org.eclipse.equinox.p2.director -repository file:///tmp/formic_121945770/update -uninstallIU org.eclim.installer.feature.group
2012-06-09 15:30:32,494 INFO  [org.formic.util.CommandExecutor] java -Xmx256M -jar /home/vermes/eclipse-new/plugins/org.eclipse.equinox.launcher_1.2.0.v20110502.jar -clean -application org.eclipse.equinox.p2.director -repository file:///tmp/formic_121945770/update -installIU org.eclim.installer.feature.group
java.lang.RuntimeException: error:  out: 
    at org.eclim.installer.step.EclipseInfo.installInstallerPlugin(EclipseInfo.java:183)
    at org.eclim.installer.step.EclipseInfoStep$1.run(EclipseInfoStep.java:67)
    at foxtrot.AbstractWorkerThread$1.run(AbstractWorkerThread.java:40)
    at java.security.AccessController.doPrivileged(Native Method)
    at foxtrot.AbstractWorkerThread.runTask(AbstractWorkerThread.java:36)
    at foxtrot.workers.SingleWorkerThread.run(SingleWorkerThread.java:199)
    at foxtrot.workers.SingleWorkerThread.run(SingleWorkerThread.java:182)
    at java.lang.Thread.run(Thread.java:662)
Installer Context (Please include in bug reports):
  eclipse.home=/home/vermes/eclipse-new
  vim.files=/home/vermes/.vim
  vim.skip=false

And in eclipse OSGI messages I can see this:

!SESSION 2012-06-09 15:30:32.610 -----------------------------------------------
eclipse.buildId=M20120208-0800
java.version=1.6.0_24
java.vendor=Sun Microsystems Inc.
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -application org.eclipse.equinox.p2.director -repository file:///tmp/formic_121945770/update -installIU org.eclim.installer.feature.group
Command-line arguments:  -clean -application org.eclipse.equinox.p2.director -repository file:///tmp/formic_121945770/update -installIU org.eclim.installer.feature.group

!ENTRY org.eclipse.osgi 4 0 2012-06-09 15:30:36.462
!MESSAGE Bundle org.eclipse.equinox.simpleconfigurator_1.0.200.v20110815-1438 [3] is not active.

As you can see, I am using Oracle JVM 1.6.0.24

**Comment by ervandew** [comment]
I'm closing this out since eclim has now moved to a new command line installer.
