### ISSUE TITLE
Can't install eclim ubuntu trusty

### ISSUE THREAD

**Issue by vushu** [ervandew/eclim#388]
tried at first to install with the gui installer all went fine 
but couldn't run vim in eclipse
next i tried with the no gui installer which gave me this error at the bottom

vushu@vushu-Lenovo-G700:~/Downloads$ java \
>   -Dvim.files=$HOME/.vim \
>   -Declipse.home=/opt/eclipse \
>   -jar eclim_2.4.1.jar install
Buildfile: installer.xml
2015-02-03 18:58:14,895 INFO  [ANT] [eclim:unattended] Installing eclim installer feature (may take a few moments).
2015-02-03 18:58:14,932 INFO  [org.formic.util.CommandExecutor] java -Xmx256m -XX:MaxPermSize=128m -jar /opt/eclipse/plugins/org.eclipse.equinox.launcher_1.3.0.v20140415-2008.jar -clean -application org.eclipse.equinox.p2.director -repository file:///tmp/formic_1580058645/update -installIU org.eclim.installer.feature.group
2015-02-03 18:58:31,380 INFO  [ANT] [eclim:unattended] Analyzing installed features...
2015-02-03 18:58:31,384 INFO  [org.formic.util.CommandExecutor] java -Xmx256m -XX:MaxPermSize=128m -jar /opt/eclipse/plugins/org.eclipse.equinox.launcher_1.3.0.v20140415-2008.jar -clean -application org.eclim.installer.application -info
2015-02-03 18:58:43,806 INFO  [org.eclim.installer.step.EclipseInfo] org.eclipse.m2e.logback.configuration: The org.eclipse.m2e.logback.configuration bundle was activated before the state location was initialized.  Will retry after the state location is initialized.
2015-02-03 18:58:43,908 INFO  [org.eclim.installer.step.EclipseInfo]   Profile: epp.package.java
2015-02-03 18:58:43,908 INFO  [org.eclim.installer.step.EclipseInfo] eclipse.profile=epp.package.java
2015-02-03 18:58:43,909 INFO  [org.eclim.installer.step.EclipseInfo]   Configuration: file:/home/vushu/.eclipse/org.eclipse.platform_4.4.1_1473617060_linux_gtk_x86_64/configuration/
2015-02-03 18:58:43,909 INFO  [org.eclim.installer.step.EclipseInfo] eclipse.local=/home/vushu/.eclipse/org.eclipse.platform_4.4.1_1473617060_linux_gtk_x86_64
2015-02-03 18:58:43,910 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.python.pydev.feature 3.9.1.201501081637 file:/home/vushu/.eclipse/org.eclipse.platform_4.4.1_1473617060_linux_gtk_x86_64/
2015-02-03 18:58:43,912 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclim.installer 2.4.1 file:/home/vushu/.eclipse/org.eclipse.platform_4.4.1_1473617060_linux_gtk_x86_64/
2015-02-03 18:58:43,912 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclim 2.4.1 file:/home/vushu/.eclipse/org.eclipse.platform_4.4.1_1473617060_linux_gtk_x86_64/
2015-02-03 18:58:43,912 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.m2e.logback.feature 1.5.0.20140606-0033 file:/opt/eclipse/
2015-02-03 18:58:43,912 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.mylyn.wikitext_feature 2.2.0.v20140905-1515 file:/opt/eclipse/
2015-02-03 18:58:43,913 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.mylyn.cvs 1.5.0.v20140702-2223 file:/opt/eclipse/
2015-02-03 18:58:43,913 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.mylyn.hudson 1.5.0.v20140702-2228 file:/opt/eclipse/
2015-02-03 18:58:43,913 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.recommenders.rcp.feature 2.1.9.v20140917-1240 file:/opt/eclipse/
2015-02-03 18:58:43,913 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.mylyn.tasks.ide 3.13.0.v20140704-0050 file:/opt/eclipse/
2015-02-03 18:58:43,913 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.emf.ecore 2.10.1.v20140901-1043 file:/opt/eclipse/
2015-02-03 18:58:43,914 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.mylyn.builds 1.5.0.v20140830-1416 file:/opt/eclipse/
2015-02-03 18:58:43,914 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.mylyn.ide_feature 3.13.0.v20140702-2225 file:/opt/eclipse/
2015-02-03 18:58:43,914 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.mylyn.monitor 3.13.0.v20140702-2155 file:/opt/eclipse/
2015-02-03 18:58:43,914 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.wb.core.ui.feature 1.7.0.r44x201405021455 file:/opt/eclipse/
2015-02-03 18:58:43,914 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.mylyn.commons.notifications 1.5.0.v20140702-2248 file:/opt/eclipse/
2015-02-03 18:58:43,915 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.egit 3.4.2.201412180340-r file:/opt/eclipse/
2015-02-03 18:58:43,915 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.jgit 3.4.2.201412180340-r file:/opt/eclipse/
2015-02-03 18:58:43,915 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.mylyn.bugzilla_feature 3.13.0.v20140830-0030 file:/opt/eclipse/
2015-02-03 18:58:43,915 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.emf.common 2.10.1.v20140901-1043 file:/opt/eclipse/
2015-02-03 18:58:43,915 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.epp.package.java.feature 4.4.1.20150109-0740 file:/opt/eclipse/
2015-02-03 18:58:43,915 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.wst.xml_ui.feature 3.6.1.v201409111852 file:/opt/eclipse/
2015-02-03 18:58:43,915 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.platform 4.4.0.v20140925-0400 file:/opt/eclipse/
2015-02-03 18:58:43,916 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.egit.mylyn 3.4.2.201412180340-r file:/opt/eclipse/
2015-02-03 18:58:43,916 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.help 2.0.102.v20140925-0400 file:/opt/eclipse/
2015-02-03 18:58:43,916 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.mylyn.discovery 3.13.0.v20140820-1854 file:/opt/eclipse/
2015-02-03 18:58:43,916 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.mylyn.commons 3.13.0.v20140704-2323 file:/opt/eclipse/
2015-02-03 18:58:43,917 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.mylyn.commons.repositories.http 1.5.0.v20140702-2248 file:/opt/eclipse/
2015-02-03 18:58:43,917 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.cvs 1.4.100.v20140925-0400 file:/opt/eclipse/
2015-02-03 18:58:43,917 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.mylyn.team_feature 3.13.0.v20140702-2225 file:/opt/eclipse/
2015-02-03 18:58:43,918 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.mylyn.git 1.5.0.v20140702-2223 file:/opt/eclipse/
2015-02-03 18:58:43,918 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.epp.mpc 1.3.1.v20140908-1651 file:/opt/eclipse/
2015-02-03 18:58:43,918 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.mylyn_feature 3.13.0.v20140826-1734 file:/opt/eclipse/
2015-02-03 18:58:43,918 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.wb.layout.group.feature 1.7.0.r44x201405021517 file:/opt/eclipse/
2015-02-03 18:58:43,919 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.wb.core.feature 1.7.0.r44x201405021445 file:/opt/eclipse/
2015-02-03 18:58:43,919 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.rcp 4.4.0.v20140925-0400 file:/opt/eclipse/
2015-02-03 18:58:43,919 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.mylyn.commons.repositories 1.5.0.v20140905-0008 file:/opt/eclipse/
2015-02-03 18:58:43,920 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.m2e.feature 1.5.0.20140606-0033 file:/opt/eclipse/
2015-02-03 18:58:43,920 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.jdt 3.10.0.v20140925-0400 file:/opt/eclipse/
2015-02-03 18:58:43,920 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.mylyn.java_feature 3.13.0.v20140819-2236 file:/opt/eclipse/
2015-02-03 18:58:43,920 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.mylyn.commons.identity 1.5.0.v20140702-2248 file:/opt/eclipse/
2015-02-03 18:58:43,921 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.wb.swing.feature 1.7.0.r44x201405021531 file:/opt/eclipse/
2015-02-03 18:58:43,921 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.mylyn.versions 1.5.0.v20140702-2223 file:/opt/eclipse/
2015-02-03 18:58:43,921 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.mylyn.context_feature 3.13.0.v20140819-2236 file:/opt/eclipse/
2015-02-03 18:58:45,008 INFO  [ANT] [eclim:unattended] Finished analyzing your eclipse installation.
2015-02-03 18:58:45,011 INFO  [ANT] [eclim:unattended] Eclim features to be installed:
2015-02-03 18:58:45,011 INFO  [ANT] [eclim:unattended]   jdt
2015-02-03 18:58:45,011 INFO  [ANT] [eclim:unattended]   pydev
2015-02-03 18:58:45,077 INFO  [ANT] [eclim:shutdown] Unable to shut down eclimd (9091): java.lang.NullPointerException - null
2015-02-03 18:58:45,115 INFO  [ANT] [eclim:uninstalliu] Uninstalling org.eclim...
2015-02-03 18:58:45,115 INFO  [org.formic.util.CommandExecutor] java -Xmx256m -XX:MaxPermSize=128m -jar /opt/eclipse/plugins/org.eclipse.equinox.launcher_1.3.0.v20140415-2008.jar -clean -application org.eclipse.equinox.p2.director -uninstallIU org.eclim.feature.group
2015-02-03 18:58:58,376 INFO  [org.eclim.installer.ant.UninstallIUTask] org.eclipse.m2e.logback.configuration: The org.eclipse.m2e.logback.configuration bundle was activated before the state location was initialized.  Will retry after the state location is initialized.
2015-02-03 18:58:58,468 INFO  [org.eclim.installer.ant.UninstallIUTask] Uninstalling org.eclim.feature.group 2.4.1.
2015-02-03 18:59:00,137 INFO  [org.eclim.installer.ant.UninstallIUTask] Operation completed in 1675 ms.
2015-02-03 18:59:01,300 INFO  [ANT] [eclim:uninstalliu] Invoking p2 gc...
2015-02-03 18:59:01,301 INFO  [org.formic.util.CommandExecutor] java -Xmx256m -XX:MaxPermSize=128m -jar /opt/eclipse/plugins/org.eclipse.equinox.launcher_1.3.0.v20140415-2008.jar -clean -application org.eclipse.equinox.p2.garbagecollector.application -profile epp.package.java
2015-02-03 18:59:13,917 INFO  [org.eclim.installer.ant.UninstallIUTask] org.eclipse.m2e.logback.configuration: The org.eclipse.m2e.logback.configuration bundle was activated before the state location was initialized.  Will retry after the state location is initialized.
2015-02-03 18:59:17,198 INFO  [ANT]     [mkdir] Created dir: /tmp/formic_1580058645/update-site/plugins
2015-02-03 18:59:17,198 INFO  [ANT]     [mkdir] Created dir: /tmp/formic_1580058645/update-site/features
2015-02-03 18:59:17,389 INFO  [ANT] [eclim:unzip] Expanding: /tmp/eclim-update-site2953492289604754464.zip into /tmp/formic_1580058645/update-site
2015-02-03 18:59:17,665 INFO  [ANT] [formic:template] Evaluating template: /tmp/formic_1580058645/update-site/artifacts.xml
2015-02-03 18:59:17,684 INFO  [ANT] [formic:template] Moving 1 file to /tmp/formic_1580058645/update-site
2015-02-03 18:59:17,684 INFO  [ANT] [formic:template] Evaluating template: /tmp/formic_1580058645/update-site/content.xml
2015-02-03 18:59:17,697 INFO  [ANT] [formic:template] Moving 1 file to /tmp/formic_1580058645/update-site
2015-02-03 18:59:17,698 INFO  [ANT] [formic:template] Evaluating template: /tmp/formic_1580058645/update-site/features/org.eclim_2.4.1/feature.xml
2015-02-03 18:59:17,701 INFO  [ANT] [formic:template] Moving 1 file to /tmp/formic_1580058645/update-site/features/org.eclim_2.4.1
2015-02-03 18:59:17,729 INFO  [ANT]       [jar] Building jar: /tmp/formic_1580058645/update-site/artifacts.jar
2015-02-03 18:59:17,734 INFO  [ANT]    [delete] Deleting: /tmp/formic_1580058645/update-site/artifacts.xml
2015-02-03 18:59:17,737 INFO  [ANT]       [jar] Building jar: /tmp/formic_1580058645/update-site/content.jar
2015-02-03 18:59:17,739 INFO  [ANT]    [delete] Deleting: /tmp/formic_1580058645/update-site/content.xml
2015-02-03 18:59:17,743 INFO  [ANT]       [jar] Building jar: /tmp/formic_1580058645/update-site/features/org.eclim_2.4.1.jar
2015-02-03 18:59:17,749 INFO  [ANT]    [delete] Deleting directory /tmp/formic_1580058645/update-site/features/org.eclim_2.4.1
2015-02-03 18:59:17,753 INFO  [ANT]       [jar] Building jar: /tmp/formic_1580058645/update-site/plugins/org.eclim.core_2.4.1.jar
2015-02-03 18:59:17,807 INFO  [ANT]    [delete] Deleting directory /tmp/formic_1580058645/update-site/plugins/org.eclim.core_2.4.1
2015-02-03 18:59:17,818 INFO  [ANT]       [jar] Building jar: /tmp/formic_1580058645/update-site/plugins/org.eclim.jdt_2.4.1.jar
2015-02-03 18:59:17,967 INFO  [ANT]    [delete] Deleting directory /tmp/formic_1580058645/update-site/plugins/org.eclim.jdt_2.4.1
2015-02-03 18:59:17,980 INFO  [ANT]       [jar] Building jar: /tmp/formic_1580058645/update-site/plugins/org.eclim.pydev_2.4.1.jar
2015-02-03 18:59:17,990 INFO  [ANT]    [delete] Deleting directory /tmp/formic_1580058645/update-site/plugins/org.eclim.pydev_2.4.1
2015-02-03 18:59:17,998 INFO  [ANT]       [jar] Building jar: /tmp/formic_1580058645/update-site/plugins/org.eclim.vimplugin_2.4.1.jar
2015-02-03 18:59:18,012 INFO  [ANT]    [delete] Deleting directory /tmp/formic_1580058645/update-site/plugins/org.eclim.vimplugin_2.4.1
2015-02-03 18:59:18,019 INFO  [ANT]       [jar] Building jar: /tmp/formic_1580058645/update-site/plugins/org.eclim_2.4.1.jar
2015-02-03 18:59:18,277 INFO  [ANT]    [delete] Deleting directory /tmp/formic_1580058645/update-site/plugins/org.eclim_2.4.1
2015-02-03 18:59:18,281 INFO  [ANT] [eclim:installiu] Installing org.eclim...
2015-02-03 18:59:18,283 INFO  [org.formic.util.CommandExecutor] java -Xmx256m -XX:MaxPermSize=128m -jar /opt/eclipse/plugins/org.eclipse.equinox.launcher_1.3.0.v20140415-2008.jar -clean -application org.eclipse.equinox.p2.director -repository file:///tmp/formic_1580058645/update-site -installIU org.eclim.feature.group
2015-02-03 18:59:34,219 ERROR [ANT] 
jar:file:/home/vushu/Downloads/eclim_2.4.1.jar!/installer.xml:231: Replace: source file /opt/eclipse/plugins/org.eclim_2.4.1/bin/eclimd doesn't exist
	at org.apache.tools.ant.taskdefs.Replace.processFile(Replace.java:663)
	at org.apache.tools.ant.taskdefs.Replace.execute(Replace.java:538)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
	at net.sf.antcontrib.logic.IfTask.execute(IfTask.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.TaskAdapter.execute(TaskAdapter.java:154)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:390)
	at org.apache.tools.ant.Target.performTasks(Target.java:411)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:458)
	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:119)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:390)
	at org.apache.tools.ant.Target.performTasks(Target.java:411)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1368)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
	at org.formic.ant.Main.runBuild(Main.java:232)
	at org.formic.ant.Main.startAnt(Main.java:81)
	at org.formic.ant.Main.main(Main.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.simontuffs.onejar.Boot.run(Boot.java:306)
	at com.simontuffs.onejar.Boot.main(Boot.java:159)
2015-02-03 18:59:34,223 ERROR [ANT] 
jar:file:/home/vushu/Downloads/eclim_2.4.1.jar!/installer.xml:146: The following error occurred while executing this line:
jar:file:/home/vushu/Downloads/eclim_2.4.1.jar!/installer.xml:231: Replace: source file /opt/eclipse/plugins/org.eclim_2.4.1/bin/eclimd doesn't exist
	at org.apache.tools.ant.ProjectHelper.addLocationToBuildException(ProjectHelper.java:551)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:460)
	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:119)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:390)
	at org.apache.tools.ant.Target.performTasks(Target.java:411)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1368)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
	at org.formic.ant.Main.runBuild(Main.java:232)
	at org.formic.ant.Main.startAnt(Main.java:81)
	at org.formic.ant.Main.main(Main.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.simontuffs.onejar.Boot.run(Boot.java:306)
	at com.simontuffs.onejar.Boot.main(Boot.java:159)
Caused by: jar:file:/home/vushu/Downloads/eclim_2.4.1.jar!/installer.xml:231: Replace: source file /opt/eclipse/plugins/org.eclim_2.4.1/bin/eclimd doesn't exist
	at org.apache.tools.ant.taskdefs.Replace.processFile(Replace.java:663)
	at org.apache.tools.ant.taskdefs.Replace.execute(Replace.java:538)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
	at net.sf.antcontrib.logic.IfTask.execute(IfTask.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.TaskAdapter.execute(TaskAdapter.java:154)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:390)
	at org.apache.tools.ant.Target.performTasks(Target.java:411)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:458)
	... 22 more
2015-02-03 18:59:34,250 DEBUG [ANT] 
BUILD SUCCESSFUL
Total time: 1 minute 19 seconds
The following error occurred while executing this line:
jar:file:/home/vushu/Downloads/eclim_2.4.1.jar!/installer.xml:231: Replace: source file /opt/eclipse/plugins/org.eclim_2.4.1/bin/eclimd doesn't exist

**Comment by ervandew** [comment]
> tried at first to install with the gui installer all went fine but couldn't run vim in eclipse

Can you elaborate on what issue you ran into?

> 2015-02-03 18:59:34,219 ERROR [ANT]
> jar:file:/home/vushu/Downloads/eclim_2.4.1.jar!/installer.xml:231: Replace: source file /opt/eclipse/plugins/org.eclim_2.4.1/bin/eclimd doesn't exist

So far I can't reproduce this, but I'll play around with it some more.

**Comment by vushu** [comment]
hello my I manged to get eclimd to run by 
cd /home/vushu/.eclipse/org.eclipse.platform_4.4.1_1473617060_linux_gtk_x86_64/
./eclimd 

which is certainly a different path then  /opt/eclipse/plugins/org.eclim_2.4.1/bin/eclimd which gave the error.

eclim works in the terminal fine when i start eclimd I 
can also ping the server

but somehow I can't get vim window to run in my eclipse and my errorlog is filled with this:

![eclimerror](https://cloud.githubusercontent.com/assets/1658625/6036823/59e5fc22-ac4b-11e4-8e62-966c8ab42dc8.png)

must be something with my setup I don't really know why.

**Comment by vicaya** [comment]
I encountered the same error installing eclim 2.5 and eclipse 4.5.2 on an Ubuntu 16.04 VM running on VMware Fusion. It turns out that Fusion created the default user with almost every group in the world _but_ "users", which causes the installer to fail as the relevant eclipse directories has permission 0775 owned by root:users. The workaround is simple:

    sudo usermod -a -G users

and logout/login and try to run the installer again.

IMO, the installer needs to be fixed to check error on every command and throw sensible errors (permission instead of "doesn't exist").

**Comment by Bost** [comment]
https://groups.google.com/forum/#!msg/eclim-user/vM8pyXP4WXI/6k1kNlO3AQAJ

> The eclim gui installer does not support the eclipse file layout 
> created by the eclipse gui installer. If you use one of the .tar.gz 
> eclipse distributions instead, that should resolve the problem.
