### ISSUE TITLE
is the Eclipse remote java debugging supported ?

### ISSUE THREAD

**Issue by syl-00101001** [ervandew/eclim#390]
Hi,
i did managed to run a project from :ProjectRun
but have difficulties with debug

into eclipse
on my project i do

Debug as.. Debug configurations.. new.. standard socket listen (8000)

into vim, i do

:JavaDebugStart localhost 8000
it takes 10 seconds average then outputs "Debugging session started."
but nothing happens and if i try to step it outputs "No thread available for stepping."

here's the log from eclimd:

2015-02-23 03:49:28,215 INFO  [org.eclim.plugin.jdt.command.debug.context.DebuggerContext] Starting debug session at localhost:8000 for vim instance: DEBUG

i can check without any problem the breakpoints list, the only remaining problem is to actually launch the debugging session or thread.
Also, if it's unsupported, do you think there's a way to obtain all the CLI arguments necessary to launch debugging session from eclipse ?

**Comment by ervandew** [comment]
What OS are you on?
Can you reproduce this problem with a small sample project?

**Comment by syl-00101001** [comment]
It looks like the same problem occurs on both Ubuntu 14.10, MacOSX 10.9, on which both very recent version of eclipse is installed (from the Eclipse Luna SR1a "IDE for Java Developers" download). I tried with a libgdx project at first but I can reproduce the problem with a bare minimum Java Project created from eclipse using only System.out.println.
eclipse.buildId=4.4.1.M20140925-0400
eclim.version: 2.4.1.3-ge91dcb4


Here's the log if you immediately do :JavaDebugStop or exit from vim

2015-02-25 19:20:52,626 INFO  [org.eclim.plugin.jdt.command.debug.context.DebuggerContext] Starting debug session at localhost:8000 for vim instance: TESTDEBUG
2015-02-25 19:21:27,765 INFO  [org.eclim.plugin.jdt.command.debug.context.DebuggerContext] Stopping debug session
2015-02-25 19:21:30,766 ERROR [org.eclim.command.Main] Command failed
org.eclipse.debug.core.DebugException: org.eclipse.jdi.TimeoutException: Timeout occurred while waiting for packet 44. occurred disconnecting from VM.
	at org.eclipse.jdt.internal.debug.core.model.JDIDebugElement.throwDebugException(JDIDebugElement.java:258)
	at org.eclipse.jdt.internal.debug.core.model.JDIDebugElement.requestFailed(JDIDebugElement.java:197)
	at org.eclipse.jdt.internal.debug.core.model.JDIDebugElement.targetRequestFailed(JDIDebugElement.java:177)
	at org.eclipse.jdt.internal.debug.core.model.JDIDebugTarget.disconnect(JDIDebugTarget.java:782)
	at org.eclim.plugin.jdt.command.debug.context.DebuggerContext.stop(DebuggerContext.java:186)
	at org.eclim.plugin.jdt.command.debug.DebugStopCommand.execute(DebugStopCommand.java:49)
	at org.eclim.command.Main$1.run(Main.java:100)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:136)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3983)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3660)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
Caused by: org.eclipse.jdi.TimeoutException: Timeout occurred while waiting for packet 44.
	at org.eclipse.jdi.internal.connect.PacketReceiveManager.getReply(PacketReceiveManager.java:186)
	at org.eclipse.jdi.internal.connect.PacketReceiveManager.getReply(PacketReceiveManager.java:197)
	at org.eclipse.jdi.internal.MirrorImpl.requestVM(MirrorImpl.java:191)
	at org.eclipse.jdi.internal.MirrorImpl.requestVM(MirrorImpl.java:267)
	at org.eclipse.jdi.internal.VirtualMachineImpl.dispose(VirtualMachineImpl.java:676)
	at org.eclipse.jdt.internal.debug.core.model.JDIDebugTarget.disconnect(JDIDebugTarget.java:775)
	... 28 more
