### ISSUE TITLE
eclimd: java.lang.IllegalArgumentException when editing a .java file outside classpath

### ISSUE THREAD

**Issue by ackalker** [ervandew/eclim#415]
Following the wonderful Getting Started guide, I accidentally created the file `<project>/org/test/TestMain.java` instead of `<project>/src/java/org/test/TestMain.java`, outside of the src/java directory mentioned in the example.
Saving the file after adding `System.` to the main method resulted in eclimd throwing the exception mentioned above.

I'm using Arch Linux, eclim-git from the AUR (PKGBUILD patched for the renamed Eclipse home directory, /usr/share/eclipse -> /usr/lib/eclipse).

The relevant part of the log from eclimd:

```
2015-07-31 20:12:48,829 INFO  [org.eclim.eclipse.EclimDaemon] Eclim Server Started on: 127.0.0.1:9091
2015-07-31 20:24:51,256 ERROR [org.eclim.command.Main] Command failed
java.lang.IllegalArgumentException: Source file 'org/test/TestMain.java' not found in any of the project's designated source directories defined in the project's .classpath file.
	at org.eclim.plugin.jdt.util.JavaUtils.getCompilationUnit(JavaUtils.java:226)
	at org.eclim.plugin.jdt.command.src.SrcUpdateCommand.execute(SrcUpdateCommand.java:82)
	at org.eclim.command.Main$1.run(Main.java:100)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3794)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3433)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
	at org.eclim.eclipse.EclimApplication.start(EclimApplication.java:128)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.equinox.internal.app.MainApplicationLauncher.run(MainApplicationLauncher.java:32)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
NGSession 1: 127.0.0.1: org.eclim.command.Main exited with status 1
```

As I was no longer sure if the eclim session still existed, I quit vim and shut down eclimd at this point.

**Comment by ackalker** [comment]
Moving the org directory below src/java, I was able to complete the example without any further problems.

**Comment by ervandew** [comment]
That error is expected and doesn't affect eclimd's ability to continue handling futher requests. Moving the file without restarting eclimd should have worked fine as well.
