### ISSUE TITLE
Does not install with Java 8

### ISSUE THREAD

**Issue by dc-mak** [ervandew/eclim#418]
java.lang.RuntimeException: error: Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
 out: An error has occurred. See the log file
C:\Users\Name\.p2\pool\configuration\1438965599143.log.
	at org.eclim.installer.step.EclipseInfo.installInstallerPlugin(EclipseInfo.java:183)
	at org.eclim.installer.step.EclipseInfoStep$1.run(EclipseInfoStep.java:67)
	at foxtrot.AbstractWorkerThread$1.run(AbstractWorkerThread.java:40)
	at java.security.AccessController.doPrivileged(Native Method)
	at foxtrot.AbstractWorkerThread.runTask(AbstractWorkerThread.java:36)
	at foxtrot.workers.SingleWorkerThread.run(SingleWorkerThread.java:199)
	at foxtrot.workers.SingleWorkerThread.run(SingleWorkerThread.java:182)
	at java.lang.Thread.run(Thread.java:745)

and the corresonding log

!SESSION 2015-08-07 17:39:58.951 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_45
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_GB
Framework arguments:  -application org.eclipse.equinox.p2.director -repository file://C:\Users\Name\AppData\Local\Temp\formic_344043624\update -installIU org.eclim.installer.feature.group
Command-line arguments:  -clean -application org.eclipse.equinox.p2.director -repository file://C:\Users\Name\AppData\Local\Temp\formic_344043624\update -installIU org.eclim.installer.feature.group

!ENTRY org.eclipse.osgi 4 0 2015-08-07 17:39:59.402
!MESSAGE Application error
!STACK 1
java.lang.IllegalStateException: Unable to acquire application service. Ensure that the org.eclipse.core.runtime bundle is resolved and started (see config.ini).
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:78)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)

Any suggestions?

**Comment by si-mikey** [comment]
I am having this same issue the only thing i can think of that might fix this is to compile from source yourself but before that go to this line  and remove the reference to MaxPermSize as java 1.8 has deprecated this. https://github.com/ervandew/eclim/blob/e91dcb482d3024a233ce6a212e16ea8ad1209d50/org.eclim.installer/java/org/eclim/installer/step/command/Command.java#L57

**Comment by ervandew** [comment]
I haven't had time to test this on windows, but I wasn't able to reproduce it on linux.

> I am having this same issue the only thing i can think of that might fix this is to compile from source yourself

I highly doubt that is the issue. This isn't a class version error, NoClassDefFound, or anything like that which would lead me to believe that the byte code is the problem. This looks like an issue with the eclipse install in some way.

> but before that go to this line and remove the reference to MaxPermSize as java 1.8 has deprecated this

That message is just a warning, not an error. It has no affect on this issue.

**Comment by ervandew** [comment]
@dc-mak 
What version of Windows are you on?
What version of eclipse are you using and how did you install it? Which eclipse bundle did you install?

**Comment by si-mikey** [comment]
I'm getting that same error on MacOSx Yosemite

**Comment by ervandew** [comment]
@si-mikey 
Can you include which version of eclipse you've installed and which bundle it is?

**Comment by si-mikey** [comment]
I'm running Eclipse IDE for java developers and its Mars released 4.5.0. Build ID: 20150621-1200. And Im running java version 1.8.0_60.

**Comment by dc-mak** [comment]
I was on Windows 8, now on Windows 10. Installed Eclipse 4.5 Mars (the Java IDE for Developers bundle) with the standard Oomph installer.

`java -jar .\eclim_2.5.0.jar
Buildfile: installer.xml
2015-10-25 10:11:58,283 INFO  [org.formic.Installer] Running Installer...
2015-10-25 10:12:05,301 INFO  [org.formic.util.CommandExecutor] vim.bat -f -X -u NONE -U NONE --cmd redir! > C:/Users/Dhruv/AppData/Local/Temp/eclim_installer3801370618423275231.tmp | silent! echo &rtp | quit
2015-10-25 10:12:19,475 INFO  [org.formic.util.CommandExecutor] java -Xmx256m -XX:MaxPermSize=128m -jar C:\Users\Dhruv\.p2\pool\plugins\org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar -clean -application org.eclipse.equinox.p2.director -repository file://C:\Users\Dhruv\AppData\Local\Temp\formic_695988467\update -installIU org.eclim.installer.feature.group
2015-10-25 10:12:21,398 WARN  [org.eclim.installer.step.EclipseInfo] Error installing eclim installer feature, attempting uninstall/reinstall.
2015-10-25 10:12:21,406 INFO  [org.formic.util.CommandExecutor] java -Xmx256m -XX:MaxPermSize=128m -jar C:\Users\Dhruv\.p2\pool\plugins\org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar -clean -application org.eclipse.equinox.p2.director -repository file://C:\Users\Dhruv\AppData\Local\Temp\formic_695988467\update -uninstallIU org.eclim.installer.feature.group
2015-10-25 10:12:23,259 INFO  [org.formic.util.CommandExecutor] java -Xmx256m -XX:MaxPermSize=128m -jar C:\Users\Dhruv\.p2\pool\plugins\org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar -clean -application org.eclipse.equinox.p2.director -repository file://C:\Users\Dhruv\AppData\Local\Temp\formic_695988467\update -installIU org.eclim.installer.feature.group
java.lang.RuntimeException: error: Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
 out: An error has occurred. See the log file
C:\Users\Dhruv\.p2\pool\configuration\1445767940572.log.
        at org.eclim.installer.step.EclipseInfo.installInstallerPlugin(EclipseInfo.java:183)
        at org.eclim.installer.step.EclipseInfoStep$1.run(EclipseInfoStep.java:67)
        at foxtrot.AbstractWorkerThread$1.run(AbstractWorkerThread.java:40)
        at java.security.AccessController.doPrivileged(Native Method)
        at foxtrot.AbstractWorkerThread.runTask(AbstractWorkerThread.java:36)
        at foxtrot.workers.SingleWorkerThread.run(SingleWorkerThread.java:199)
        at foxtrot.workers.SingleWorkerThread.run(SingleWorkerThread.java:182)
        at java.lang.Thread.run(Unknown Source)
Installer Context (Please include in bug reports):
  eclipse.home=C:/Users/Dhruv/.p2/pool
  vim.files=C:/Users/Dhruv/vimfiles
  vim.skip=false
2015-10-25 10:12:38,257 INFO  [org.formic.Installer] Installer Finished.
2015-10-25 10:12:38,265 DEBUG [ANT]
BUILD SUCCESSFUL
Total time: 40 seconds
2015-10-25 10:12:38,326 WARN  [ANT]      [echo] Installation canceled.`

**Comment by ervandew** [comment]
@dc-mak 
Note these lines in the output you posted:

    out: An error has occurred. See the log file
    C:\Users\Dhruv\.p2\pool\configuration\1445767940572.log.

Can you post the contents of the file referenced there so we can see what caused the failure?

**Comment by ervandew** [comment]
@dc-mak 
Sorry, looks like you did so, at least with a previous attempt, in the original ticket description (I was confusing this ticket with another one). I'll have to find a way to get a hold of Windows 10 so I can try to mirror your env as best as possible.

**Comment by ervandew** [comment]
@dc-mak 
Can you also try installing eclim against a fresh .zip version of eclipse (don't use their installer) and unpack it to a new location?

**Comment by dareTake** [comment]
I'm receiving the same error via the graphical installer. 

```
java.lang.RuntimeException: error: Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
 out: An error has occurred. See the log file
/Applications/Eclipse.app/Contents/Eclipse/configuration/1446621455215.log.
	at org.eclim.installer.step.EclipseInfo.gatherEclipseInfo(EclipseInfo.java:260)
	at org.eclim.installer.step.EclipseInfoStep$1.run(EclipseInfoStep.java:72)
	at foxtrot.AbstractWorkerThread$1.run(AbstractWorkerThread.java:40)
	at java.security.AccessController.doPrivileged(Native Method)
	at foxtrot.AbstractWorkerThread.runTask(AbstractWorkerThread.java:36)
	at foxtrot.workers.SingleWorkerThread.run(SingleWorkerThread.java:199)
	at foxtrot.workers.SingleWorkerThread.run(SingleWorkerThread.java:182)
	at java.lang.Thread.run(Thread.java:745)
```

As for the 1446621455215.log,
```
!SESSION 2015-11-04 12:47:35.148 -----------------------------------------------
eclipse.buildId=4.5.1.M20150904-0015
java.version=1.8.0_40
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -application org.eclim.installer.application -info
Command-line arguments:  -clean -application org.eclim.installer.application -info

!ENTRY org.eclipse.osgi 4 0 2015-11-04 12:47:38.473
!MESSAGE Application error
!STACK 1
java.lang.RuntimeException: Application "org.eclim.installer.application" could not be found in the registry. The applications available are: org.eclipse.ant.core.antRunner, org.eclipse.ant.ui.antRunner, org.eclipse.e4.ui.workbench.swt.E4Application, org.eclipse.e4.ui.workbench.swt.GenTopic, org.eclipse.equinox.app.error, org.eclipse.equinox.p2.director, org.eclipse.equinox.p2.garbagecollector.application, org.eclipse.equinox.p2.publisher.InstallPublisher, org.eclipse.equinox.p2.publisher.EclipseGenerator, org.eclipse.equinox.p2.publisher.ProductPublisher, org.eclipse.equinox.p2.publisher.FeaturesAndBundlesPublisher, org.eclipse.equinox.p2.reconciler.application, org.eclipse.equinox.p2.repository.repo2runnable, org.eclipse.equinox.p2.repository.metadataverifier, org.eclipse.equinox.p2.artifact.repository.mirrorApplication, org.eclipse.equinox.p2.metadata.repository.mirrorApplication, org.eclipse.equinox.p2.touchpoint.natives.nativePackageExtractor, org.eclipse.equinox.p2.updatesite.UpdateSitePublisher, org.eclipse.equinox.p2.publisher.UpdateSitePublisher, org.eclipse.equinox.p2.publisher.CategoryPublisher, org.eclipse.help.base.infocenterApplication, org.eclipse.help.base.helpApplication, org.eclipse.help.base.indexTool, org.eclipse.jdt.apt.core.aptBuild, org.eclipse.jdt.core.JavaCodeFormatter, org.eclipse.jdt.core.JavaIndexer, org.eclipse.pde.build.Build, org.eclipse.ui.ide.workbench.
	at org.eclipse.equinox.internal.app.EclipseAppContainer.startDefaultApp(EclipseAppContainer.java:248)
	at org.eclipse.equinox.internal.app.MainApplicationLauncher.run(MainApplicationLauncher.java:29)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)

!ENTRY org.eclipse.equinox.ds 2 0 2015-11-04 12:47:48.927
!MESSAGE Getting a lock required more than 10000 ms. There might be a synchronization problem in this callstack or just the build/dispose process of some components took too long! 
!STACK 0
java.lang.Exception: Debug stacktrace
	at org.eclipse.equinox.internal.ds.InstanceProcess.getLock(InstanceProcess.java:120)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:560)
	at org.eclipse.equinox.internal.ds.ServiceReg.getService(ServiceReg.java:53)
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse$1.run(ServiceFactoryUse.java:212)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:210)
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.getService(ServiceFactoryUse.java:111)
	at org.eclipse.osgi.internal.serviceregistry.ServiceConsumer$2.getService(ServiceConsumer.java:45)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:496)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.getService(ServiceRegistry.java:461)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.getService(BundleContextImpl.java:619)
	at org.eclipse.equinox.internal.p2.core.ProvisioningAgent.addingService(ProvisioningAgent.java:159)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:1)
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
	at org.osgi.util.tracker.AbstractTracked.trackInitial(AbstractTracked.java:183)
	at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:318)
	at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:261)
	at org.eclipse.equinox.internal.p2.core.ProvisioningAgent.getService(ProvisioningAgent.java:66)
	at org.eclipse.equinox.internal.p2.engine.ProfilePreferences.doSave(ProfilePreferences.java:120)
	at org.eclipse.equinox.internal.p2.engine.ProfilePreferences$SaveJob.run(ProfilePreferences.java:49)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by dareTake** [comment]
And this is for the unattended install, 

'''
2015-11-04 13:07:18,931 INFO  [ANT] [eclim:unattended] Installing eclim installer feature (may take a few moments).
2015-11-04 13:07:18,948 INFO  [org.formic.util.CommandExecutor] java -Xmx256m -XX:MaxPermSize=128m -Dhttp.nonProxyHosts=local|*.local|169.254/16|*.169.254/16 -jar /Applications/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar -clean -application org.eclipse.equinox.p2.director -repository file:///var/folders/9j/msspmsxs6754brgck7_pyz980000gn/T/formic_104360830/update -installIU org.eclim.installer.feature.group
2015-11-04 13:07:33,798 INFO  [ANT] [eclim:unattended] Analyzing installed features...
2015-11-04 13:07:33,799 INFO  [org.formic.util.CommandExecutor] java -Xmx256m -XX:MaxPermSize=128m -Dhttp.nonProxyHosts=local|*.local|169.254/16|*.169.254/16 -jar /Applications/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar -clean -application org.eclim.installer.application -info
2015-11-04 13:07:48,511 INFO  [org.eclim.installer.step.EclipseInfo] An error has occurred. See the log file
2015-11-04 13:07:48,511 INFO  [org.eclim.installer.step.EclipseInfo] /Applications/Eclipse.app/Contents/Eclipse/configuration/1446622653989.log.
2015-11-04 13:07:48,537 ERROR [ANT]
jar:file:/Users/dare/utils/eclim_2.5.0.jar!/installer.xml:134: java.lang.RuntimeException: error: Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
 out: An error has occurred. See the log file
/Applications/Eclipse.app/Contents/Eclipse/configuration/1446622653989.log.
	at org.eclim.installer.ant.UnattendedInstallTask.execute(UnattendedInstallTask.java:73)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:390)
	at org.apache.tools.ant.Target.performTasks(Target.java:411)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1368)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
	at org.formic.ant.Main.runBuild(Main.java:232)
	at org.formic.ant.Main.startAnt(Main.java:81)
	at org.formic.ant.Main.main(Main.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.simontuffs.onejar.Boot.run(Boot.java:306)
	at com.simontuffs.onejar.Boot.main(Boot.java:159)
Caused by: java.lang.RuntimeException: error: Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
 out: An error has occurred. See the log file
/Applications/Eclipse.app/Contents/Eclipse/configuration/1446622653989.log.
	at org.eclim.installer.step.EclipseInfo.gatherEclipseInfo(EclipseInfo.java:260)
	at org.eclim.installer.ant.UnattendedInstallTask.execute(UnattendedInstallTask.java:68)
	... 22 more
2015-11-04 13:07:48,545 DEBUG [ANT]
BUILD SUCCESSFUL
Total time: 29 seconds
java.lang.RuntimeException: error: Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
 out: An error has occurred. See the log file
/Applications/Eclipse.app/Contents/Eclipse/configuration/1446622653989.log.
'''

**Comment by dareTake** [comment]
FYI, I have managed to make it work with the Eclipse Platform Binary zip from the site. 
It might be that the new [installer](https://wiki.eclipse.org/Eclipse_Installer) is messing up the installation.

**Comment by sideshowbarker** [comment]
> FYI, I have managed to make it work with the Eclipse Platform Binary zip from the site. 
> It might be that the new installer is messing up the installation.

Yeah, I also was getting the "`ignoring option MaxPermSize=128m; support was removed in 8.0`" error after having used the `https://www.eclipse.org/downloads/download.php?file=/oomph/epp/mars/R1a/eclipse-inst-mac64.tar.gz` Eclipse installer.

So the way I got things working in my OSX environment is this:
```
brew install ant
brew cask install eclipse-java
git clone git://github.com/ervandew/eclim.git
cd eclim
ant -Declipse.home=/opt/homebrew-cask/Caskroom/eclipse-java/4.5.1/Eclipse.app/Contents/Eclipse
```

**Comment by mitermayer** [comment]
Same error on debian

**Comment by dc-mak** [comment]
I can confirm after doing a regular extract install instead of with the Oomph installer, the issue disappears.
