### ISSUE TITLE
Error installing to STS 3.7.0.RELEASE : Unresolved requirement: Require-Bundle: org.eclipse.core.runtime

### ISSUE THREAD

**Issue by WilliamLightner** [ervandew/eclim#426]
Straight-forward attempt to install to WINDOWS 7/64 bit.

Installing to:
C:\Program Files\Eclipse\spring-tool-suite-3.7.0.RELEASE-e4.5-win32-x86_64\sts-3.7.0.RELEASE

Other information:

Eclipse itself seems to have problems pulling & installing updates.  I've seen this on at least 2 machines here, and heard of other machines having the same problem.

I got with networking and they dropped the proxy to attempt to fix the above, with no improvement.  So this *might* be an Eclipse issue, but I haven't found anything on the net that attributes it to anything but proxy problems.  Since I attempted without a proxy, this doesn't seem to be the answer to that.  

The question is, is this a failure to pull a required dependency that is failing?  Or is something "missing" from the STS 3.7 Eclipse?  Or ...?

Thanks

-->java -jar eclim_2.5.0.jar
Buildfile: installer.xml
2015-08-21 10:24:40,643 INFO  [org.formic.Installer] Running Installer...
2015-08-21 10:24:46,758 INFO  [org.formic.util.CommandExecutor] vim.bat -f -X -u NONE -U NONE --cmd redir! > C:/Users/jisajl1/AppData/Local/Te
_installer9051742650168345425.tmp | silent! echo &rtp | quit
2015-08-21 10:25:43,797 INFO  [org.formic.util.CommandExecutor] java -Xmx256m -XX:MaxPermSize=128m -jar C:\Program Files\Eclipse\spring-tool-s
.0.RELEASE-e4.5-win32-x86_64\sts-3.7.0.RELEASE\plugins\org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar -clean -application org.eclipse
.p2.director -repository file://C:\Users\jisajl1\AppData\Local\Temp\formic_960551375\update -installIU org.eclim.installer.feature.group
2015-08-21 10:26:10,308 WARN  [org.eclim.installer.step.EclipseInfo] Error installing eclim installer feature, attempting uninstall/reinstall.
2015-08-21 10:26:10,319 INFO  [org.formic.util.CommandExecutor] java -Xmx256m -XX:MaxPermSize=128m -jar C:\Program Files\Eclipse\spring-tool-s
.0.RELEASE-e4.5-win32-x86_64\sts-3.7.0.RELEASE\plugins\org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar -clean -application org.eclipse
.p2.director -repository file://C:\Users\jisajl1\AppData\Local\Temp\formic_960551375\update -uninstallIU org.eclim.installer.feature.group
2015-08-21 10:26:36,568 INFO  [org.formic.util.CommandExecutor] java -Xmx256m -XX:MaxPermSize=128m -jar C:\Program Files\Eclipse\spring-tool-s
.0.RELEASE-e4.5-win32-x86_64\sts-3.7.0.RELEASE\plugins\org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar -clean -application org.eclipse
.p2.director -repository file://C:\Users\jisajl1\AppData\Local\Temp\formic_960551375\update -installIU org.eclim.installer.feature.group
java.lang.RuntimeException: error: org.osgi.framework.BundleException: Could not resolve module: org.eclipse.objectteams.otequinox [1327]
  Unresolved requirement: Require-Bundle: org.eclipse.core.runtime
    -> Bundle-SymbolicName: org.eclipse.core.runtime; bundle-version="3.11.0.v20150405-1723"; singleton:="true"
       org.eclipse.core.runtime [423]
         Unresolved requirement: Require-Bundle: org.eclipse.core.jobs; bundle-version="[3.2.0,4.0.0)"; visibility:="reexport"
           -> Bundle-SymbolicName: org.eclipse.core.jobs; bundle-version="3.7.0.v20150330-2103"; singleton:="true"
              org.eclipse.core.jobs [418]
                Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=1.7))"

        at org.eclipse.osgi.container.Module.start(Module.java:434)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:392)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:411)
        at org.eclipse.equinox.internal.simpleconfigurator.ConfigApplier.startBundles(ConfigApplier.java:438)
        at org.eclipse.equinox.internal.simpleconfigurator.ConfigApplier.install(ConfigApplier.java:111)
        at org.eclipse.equinox.internal.simpleconfigurator.SimpleConfiguratorImpl.applyConfiguration(SimpleConfiguratorImpl.java:191)
        at org.eclipse.equinox.internal.simpleconfigurator.SimpleConfiguratorImpl.applyConfiguration(SimpleConfiguratorImpl.java:205)
        at org.eclipse.equinox.internal.simpleconfigurator.Activator.start(Activator.java:60)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:771)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:764)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:721)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:941)
        at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:318)
        at org.eclipse.osgi.container.Module.doStart(Module.java:571)
        at org.eclipse.osgi.container.Module.start(Module.java:439)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1562)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
        at org.eclipse.osgi.container.SystemModule.startWorker(SystemModule.java:242)
        at org.eclipse.osgi.container.Module.doStart(Module.java:571)
        at org.eclipse.osgi.container.Module.start(Module.java:439)
        at org.eclipse.osgi.container.SystemModule.start(SystemModule.java:172)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:392)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:411)
        at org.eclipse.osgi.launch.Equinox.start(Equinox.java:115)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.startup(EclipseStarter.java:318)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:231)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
 out: An error has occurred. See the log file
C:\Program Files\Eclipse\spring-tool-suite-3.7.0.RELEASE-e4.5-win32-x86_64\sts-3.7.0.RELEASE\configuration\1440170744217.log.
        at org.eclim.installer.step.EclipseInfo.installInstallerPlugin(EclipseInfo.java:183)
        at org.eclim.installer.step.EclipseInfoStep$1.run(EclipseInfoStep.java:67)
        at foxtrot.AbstractWorkerThread$1.run(AbstractWorkerThread.java:40)
        at java.security.AccessController.doPrivileged(Native Method)
        at foxtrot.AbstractWorkerThread.runTask(AbstractWorkerThread.java:36)
        at foxtrot.workers.SingleWorkerThread.run(SingleWorkerThread.java:199)
        at foxtrot.workers.SingleWorkerThread.run(SingleWorkerThread.java:182)
        at java.lang.Thread.run(Unknown Source)
Installer Context (Please include in bug reports):
  eclipse.home=C:/Program Files/Eclipse/spring-tool-suite-3.7.0.RELEASE-e4.5-win32-x86_64/sts-3.7.0.RELEASE
  vim.files=c:/PROGRA~2/Vim/vim74
  vim.skip=false
2015-08-21 10:27:08,837 INFO  [org.formic.Installer] Installer Finished.
2015-08-21 10:27:08,843 DEBUG [ANT]
BUILD SUCCESSFUL
Total time: 2 minutes 28 seconds
2015-08-21 10:27:08,882 WARN  [ANT]      [echo] Installation canceled.

E:\Downloads\vim\eclim
Fri 08/21/2015 10:27:08.95
-->set eclipsee
Environment variable eclipsee not defined

E:\Downloads\vim\eclim
Fri 08/21/2015 10:28:33.55
-->set ECLIPSE_HOME=

E:\Downloads\vim\eclim
Fri 08/21/2015 10:29:14.09
-->set ECLIPSE_HOME=C:\Program Files\Eclipse\spring-tool-suite-3.7.0.RELEASE-e4.5-win32-x86_64\sts-3.7.0.RELEASE

E:\Downloads\vim\eclim
Fri 08/21/2015 10:29:20.83
-->java -jar eclim_2.5.0.jar
Buildfile: installer.xml
2015-08-21 10:29:27,649 INFO  [org.formic.Installer] Running Installer...
2015-08-21 10:29:33,618 INFO  [org.formic.util.CommandExecutor] vim.bat -f -X -u NONE -U NONE --cmd redir! > C:/Users/jisajl1/AppData/Local/Te
_installer482657144400100567.tmp | silent! echo &rtp | quit
2015-08-21 10:29:43,325 INFO  [org.formic.util.CommandExecutor] java -Xmx256m -XX:MaxPermSize=128m -jar C:\Program Files\Eclipse\spring-tool-s
.0.RELEASE-e4.5-win32-x86_64\sts-3.7.0.RELEASE\plugins\org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar -clean -application org.eclipse
.p2.director -repository file://C:\Users\jisajl1\AppData\Local\Temp\formic_1529778230\update -installIU org.eclim.installer.feature.group
2015-08-21 10:30:12,357 WARN  [org.eclim.installer.step.EclipseInfo] Error installing eclim installer feature, attempting uninstall/reinstall.
2015-08-21 10:30:12,366 INFO  [org.formic.util.CommandExecutor] java -Xmx256m -XX:MaxPermSize=128m -jar C:\Program Files\Eclipse\spring-tool-s
.0.RELEASE-e4.5-win32-x86_64\sts-3.7.0.RELEASE\plugins\org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar -clean -application org.eclipse
.p2.director -repository file://C:\Users\jisajl1\AppData\Local\Temp\formic_1529778230\update -uninstallIU org.eclim.installer.feature.group
2015-08-21 10:30:40,673 INFO  [org.formic.util.CommandExecutor] java -Xmx256m -XX:MaxPermSize=128m -jar C:\Program Files\Eclipse\spring-tool-s
.0.RELEASE-e4.5-win32-x86_64\sts-3.7.0.RELEASE\plugins\org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar -clean -application org.eclipse
.p2.director -repository file://C:\Users\jisajl1\AppData\Local\Temp\formic_1529778230\update -installIU org.eclim.installer.feature.group
java.lang.RuntimeException: error: org.osgi.framework.BundleException: Could not resolve module: org.eclipse.objectteams.otequinox [1327]
  Unresolved requirement: Require-Bundle: org.eclipse.core.runtime
    -> Bundle-SymbolicName: org.eclipse.core.runtime; bundle-version="3.11.0.v20150405-1723"; singleton:="true"
       org.eclipse.core.runtime [423]
         Unresolved requirement: Require-Bundle: org.eclipse.core.jobs; bundle-version="[3.2.0,4.0.0)"; visibility:="reexport"
           -> Bundle-SymbolicName: org.eclipse.core.jobs; bundle-version="3.7.0.v20150330-2103"; singleton:="true"
              org.eclipse.core.jobs [418]
                Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=1.7))"

        at org.eclipse.osgi.container.Module.start(Module.java:434)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:392)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:411)
        at org.eclipse.equinox.internal.simpleconfigurator.ConfigApplier.startBundles(ConfigApplier.java:438)
        at org.eclipse.equinox.internal.simpleconfigurator.ConfigApplier.install(ConfigApplier.java:111)
        at org.eclipse.equinox.internal.simpleconfigurator.SimpleConfiguratorImpl.applyConfiguration(SimpleConfiguratorImpl.java:191)
        at org.eclipse.equinox.internal.simpleconfigurator.SimpleConfiguratorImpl.applyConfiguration(SimpleConfiguratorImpl.java:205)
        at org.eclipse.equinox.internal.simpleconfigurator.Activator.start(Activator.java:60)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:771)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:764)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:721)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:941)
        at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:318)
        at org.eclipse.osgi.container.Module.doStart(Module.java:571)
        at org.eclipse.osgi.container.Module.start(Module.java:439)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1562)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
        at org.eclipse.osgi.container.SystemModule.startWorker(SystemModule.java:242)
        at org.eclipse.osgi.container.Module.doStart(Module.java:571)
        at org.eclipse.osgi.container.Module.start(Module.java:439)
        at org.eclipse.osgi.container.SystemModule.start(SystemModule.java:172)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:392)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:411)
        at org.eclipse.osgi.launch.Equinox.start(Equinox.java:115)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.startup(EclipseStarter.java:318)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:231)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
 out: An error has occurred. See the log file
C:\Program Files\Eclipse\spring-tool-suite-3.7.0.RELEASE-e4.5-win32-x86_64\sts-3.7.0.RELEASE\configuration\1440170983732.log.
        at org.eclim.installer.step.EclipseInfo.installInstallerPlugin(EclipseInfo.java:183)
        at org.eclim.installer.step.EclipseInfoStep$1.run(EclipseInfoStep.java:67)
        at foxtrot.AbstractWorkerThread$1.run(AbstractWorkerThread.java:40)
        at java.security.AccessController.doPrivileged(Native Method)
        at foxtrot.AbstractWorkerThread.runTask(AbstractWorkerThread.java:36)
        at foxtrot.workers.SingleWorkerThread.run(SingleWorkerThread.java:199)
        at foxtrot.workers.SingleWorkerThread.run(SingleWorkerThread.java:182)
        at java.lang.Thread.run(Unknown Source)
Installer Context (Please include in bug reports):
  eclipse.home=C:/Program Files/Eclipse/spring-tool-suite-3.7.0.RELEASE-e4.5-win32-x86_64/sts-3.7.0.RELEASE
  vim.files=c:/PROGRA~2/Vim/vim74
  vim.skip=false

**Comment by ervandew** [comment]
I didn't have any issue running the eclim installer against STS 3.7.0 on linux, so when I get a chance I'll see if I can reproduce your issue on windows.

Are you installing against a fresh STS install? The eclipse configuration can sometimes get corrupted, so if you aren't, I'd suggest trying again with a clean STS install.

**Comment by jmaxallen** [comment]
I had the exact same 'equinox' error, multiple times.  All attempts were fresh installs (new directories but old not deleted) on Windows 7 with both 32- and 64-bit installations of Eclipse Mars or STS 3.7, Vim 7.4.  (I am installing on my D: drive while my user account with the maven caches, etc. are on the C: drive, but that shouldn't matter.)

I tried:
- STS, then Eclim
- Eclipse, Eclim (I think it showed up even here), STS
- Even tried updating from inside Eclipse

I really want to try then use Eclim.  It looks great.  I'm switching back forth with Alt-Tab, but it means extra work trying to remember the Eclipse keyboard shortcuts or creating new ones.  Ugh, compared to Vim it is so clunky.
