### ISSUE TITLE
Unable to install, "The installable unit org.eclim.feature.group has not been found."

### ISSUE THREAD

**Issue by dakrone** [ervandew/eclim#429]
Here is the full log from installation:

```
» PATH=/opt/jdk1.7.0_79/bin:$PATH JAVA_HOME=/opt/jdk1.7.0_79 java -jar ./eclim_2.5.0.jar
Buildfile: installer.xml
2015-09-08 12:41:55,716 INFO  [org.formic.Installer] Running Installer...
2015-09-08 12:41:58,950 INFO  [org.formic.util.CommandExecutor] which gvim
2015-09-08 12:41:58,956 INFO  [org.eclim.installer.step.VimStep] which gvim: out= err=which: no gvim in (/opt/jdk1.7.0_79/bin:/opt/jdk1.8.0_45/bin:/home/hinmanm/bin:/home/hinmanm/.cabal/bin:/usr/local/bin:/usr/local/sbin:/opt/jdk1.8.0_45/bin:/home/hinmanm/bin:/home/hinmanm/.cabal/bin:/usr/local/bin:/usr/local/sbin:/home/hinmanm/.gvm/vertx/current/bin:/home/hinmanm/.gvm/springboot/current/bin:/home/hinmanm/.gvm/lazybones/current/bin:/home/hinmanm/.gvm/jbossforge/current/bin:/home/hinmanm/.gvm/jbake/current/bin:/home/hinmanm/.gvm/groovyserv/current/bin:/home/hinmanm/.gvm/groovy/current/bin:/home/hinmanm/.gvm/griffon/current/bin:/home/hinmanm/.gvm/grails/current/bin:/home/hinmanm/.gvm/gradle/current/bin:/home/hinmanm/.gvm/glide/current/bin:/home/hinmanm/.gvm/gaiden/current/bin:/home/hinmanm/.gvm/crash/current/bin:/home/hinmanm/.gvm/asciidoctorj/current/bin:/opt/jdk1.8.0_45/bin:/home/hinmanm/bin:/home/hinmanm/.cabal/bin:/usr/local/bin:/usr/local/sbin:/usr/lib64/qt-3.3/bin:/usr/lib64/ccache:/opt/jdk1.8.0_45/bin:/home/hinmanm/bin:/home/hinmanm/.cabal/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/hinmanm/node_modules/.bin:/home/hinmanm/.cask/bin:/home/hinmanm/bin:/home/hinmanm/node_modules/.bin:/home/hinmanm/.cask/bin:/home/hinmanm/node_modules/.bin:/home/hinmanm/.cask/bin:/home/hinmanm/bin:/home/hinmanm/node_modules/.bin:/home/hinmanm/.cask/bin:/home/hinmanm/bin)
Checking for user vim files directory: /home/hinmanm/.vim
2015-09-08 12:42:06,388 INFO  [org.formic.util.CommandExecutor] java -Xmx256m -XX:MaxPermSize=128m -jar /usr/lib64/eclipse/plugins/org.eclipse.equinox.launcher_1.3.100.v20150826-1000.jar -clean -application org.eclipse.equinox.p2.director -repository file:///tmp/formic_273611395/update -installIU org.eclim.installer.feature.group
2015-09-08 12:42:10,678 INFO  [org.formic.util.CommandExecutor] java -Xmx256m -XX:MaxPermSize=128m -jar /usr/lib64/eclipse/plugins/org.eclipse.equinox.launcher_1.3.100.v20150826-1000.jar -clean -application org.eclim.installer.application -info
2015-09-08 12:42:14,135 INFO  [org.eclim.installer.step.EclipseInfo]   Profile: SDKProfile
2015-09-08 12:42:14,135 INFO  [org.eclim.installer.step.EclipseInfo] eclipse.profile=SDKProfile
2015-09-08 12:42:14,135 INFO  [org.eclim.installer.step.EclipseInfo]   Configuration: file:/home/hinmanm/.eclipse/org.eclipse.platform_793567567_linux_gtk_x86_64/configuration/
2015-09-08 12:42:14,135 INFO  [org.eclim.installer.step.EclipseInfo] eclipse.local=/home/hinmanm/.eclipse/org.eclipse.platform_793567567_linux_gtk_x86_64
2015-09-08 12:42:14,136 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.platform 4.5.0.v20150826-1000 file:/usr/lib64/eclipse/
2015-09-08 12:42:14,136 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.rcp 4.5.0.v20150826-1000 file:/usr/lib64/eclipse/
2015-09-08 12:42:14,136 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.help 2.1.0.v20150826-1000 file:/usr/lib64/eclipse/
2015-09-08 12:42:14,136 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.emf.ecore 2.10.2.v20150304-1000 file:/usr/lib64/eclipse/
2015-09-08 12:42:14,136 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.emf.common 2.10.1.v20150304-1000 file:/usr/lib64/eclipse/
2015-09-08 12:42:14,136 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.cvs 1.4.200.v20150826-1000 file:/usr/lib64/eclipse/dropins/cvs/
2015-09-08 12:42:14,136 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.jdt 3.11.0.v20150826-1000 file:/usr/lib64/eclipse/dropins/jdt/
2015-09-08 12:42:14,137 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.sdk 4.5.0.v20150826-1000 file:/usr/lib64/eclipse/dropins/sdk/
2015-09-08 12:42:14,137 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.pde 3.11.0.v20150826-1000 file:/usr/lib64/eclipse/dropins/sdk/
2015-09-08 12:42:14,137 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclim.installer 2.5.0 file:/home/hinmanm/.eclipse/org.eclipse.platform_793567567_linux_gtk_x86_64/
2015-09-08 12:42:18,483 INFO  [ANT] [eclim:shutdown] Unable to shut down eclimd (9091): java.lang.NullPointerException - null
2015-09-08 12:42:18,506 INFO  [ANT] [eclim:uninstalliu] Uninstalling org.eclim...
2015-09-08 12:42:18,506 INFO  [org.formic.util.CommandExecutor] java -Xmx256m -XX:MaxPermSize=128m -jar /usr/lib64/eclipse/plugins/org.eclipse.equinox.launcher_1.3.100.v20150826-1000.jar -clean -application org.eclipse.equinox.p2.director -uninstallIU org.eclim.feature.group
2015-09-08 12:42:21,811 INFO  [org.eclim.installer.ant.UninstallIUTask] Installation failed.
2015-09-08 12:42:22,493 INFO  [org.eclim.installer.ant.UninstallIUTask]
2015-09-08 12:42:22,512 WARN  [org.eclim.installer.ant.UninstallIUTask] error: The installable unit org.eclim.feature.group has not been found.
Application failed, log file location: /home/hinmanm/.eclipse/org.eclipse.platform_793567567_linux_gtk_x86_64/configuration/1441737738576.log
 out: Installation failed.

2015-09-08 12:42:22,512 ERROR [ANT]
jar:file:/home/hinmanm/Downloads/eclim_2.5.0.jar!/installer.xml:326: error: The installable unit org.eclim.feature.group has not been found.
Application failed, log file location: /home/hinmanm/.eclipse/org.eclipse.platform_793567567_linux_gtk_x86_64/configuration/1441737738576.log
 out: Installation failed.

        at org.eclim.installer.ant.UninstallIUTask.runCommand(UninstallIUTask.java:161)
        at org.eclim.installer.ant.UninstallIUTask.execute(UninstallIUTask.java:83)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
        at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
        at net.sf.antcontrib.logic.IfTask.execute(IfTask.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.TaskAdapter.execute(TaskAdapter.java:154)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
        at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:390)
        at org.apache.tools.ant.Target.performTasks(Target.java:411)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
        at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
        at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:458)
        at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:119)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
        at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:390)
        at org.apache.tools.ant.Target.performTasks(Target.java:411)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1368)
        at org.formic.wizard.step.shared.InstallAction.execute(InstallAction.java:124)
        at org.formic.wizard.step.gui.InstallStep$1.run(InstallStep.java:162)
        at foxtrot.AbstractWorkerThread$1.run(AbstractWorkerThread.java:40)
        at java.security.AccessController.doPrivileged(Native Method)
        at foxtrot.AbstractWorkerThread.runTask(AbstractWorkerThread.java:36)
        at foxtrot.workers.SingleWorkerThread.run(SingleWorkerThread.java:199)
        at foxtrot.workers.SingleWorkerThread.run(SingleWorkerThread.java:182)
        at java.lang.Thread.run(Thread.java:745)
Caused by: error: The installable unit org.eclim.feature.group has not been found.
Application failed, log file location: /home/hinmanm/.eclipse/org.eclipse.platform_793567567_linux_gtk_x86_64/configuration/1441737738576.log
 out: Installation failed.

        at org.eclim.installer.ant.UninstallIUTask.runCommand(UninstallIUTask.java:154)
        ... 46 more
2015-09-08 12:42:22,514 ERROR [ANT]
jar:file:/home/hinmanm/Downloads/eclim_2.5.0.jar!/installer.xml:145: The following error occurred while executing this line:
jar:file:/home/hinmanm/Downloads/eclim_2.5.0.jar!/installer.xml:326: error: The installable unit org.eclim.feature.group has not been found.
Application failed, log file location: /home/hinmanm/.eclipse/org.eclipse.platform_793567567_linux_gtk_x86_64/configuration/1441737738576.log
 out: Installation failed.

        at org.apache.tools.ant.ProjectHelper.addLocationToBuildException(ProjectHelper.java:551)
        at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:460)
        at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:119)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
        at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:390)
        at org.apache.tools.ant.Target.performTasks(Target.java:411)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1368)
        at org.formic.wizard.step.shared.InstallAction.execute(InstallAction.java:124)
        at org.formic.wizard.step.gui.InstallStep$1.run(InstallStep.java:162)
        at foxtrot.AbstractWorkerThread$1.run(AbstractWorkerThread.java:40)
        at java.security.AccessController.doPrivileged(Native Method)
        at foxtrot.AbstractWorkerThread.runTask(AbstractWorkerThread.java:36)
        at foxtrot.workers.SingleWorkerThread.run(SingleWorkerThread.java:199)
        at foxtrot.workers.SingleWorkerThread.run(SingleWorkerThread.java:182)
        at java.lang.Thread.run(Thread.java:745)
Caused by: jar:file:/home/hinmanm/Downloads/eclim_2.5.0.jar!/installer.xml:326: error: The installable unit org.eclim.feature.group has not been found.
Application failed, log file location: /home/hinmanm/.eclipse/org.eclipse.platform_793567567_linux_gtk_x86_64/configuration/1441737738576.log
 out: Installation failed.

        at org.eclim.installer.ant.UninstallIUTask.runCommand(UninstallIUTask.java:161)
        at org.eclim.installer.ant.UninstallIUTask.execute(UninstallIUTask.java:83)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
        at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
        at net.sf.antcontrib.logic.IfTask.execute(IfTask.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.TaskAdapter.execute(TaskAdapter.java:154)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
        at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:390)
        at org.apache.tools.ant.Target.performTasks(Target.java:411)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
        at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
        at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:458)
        ... 19 more
Caused by: error: The installable unit org.eclim.feature.group has not been found.
Application failed, log file location: /home/hinmanm/.eclipse/org.eclipse.platform_793567567_linux_gtk_x86_64/configuration/1441737738576.log
 out: Installation failed.

        at org.eclim.installer.ant.UninstallIUTask.runCommand(UninstallIUTask.java:154)
        ... 46 more
jar:file:/home/hinmanm/Downloads/eclim_2.5.0.jar!/installer.xml:145: The following error occurred while executing this line:
jar:file:/home/hinmanm/Downloads/eclim_2.5.0.jar!/installer.xml:326: error: The installable unit org.eclim.feature.group has not been found.
Application failed, log file location: /home/hinmanm/.eclipse/org.eclipse.platform_793567567_linux_gtk_x86_64/configuration/1441737738576.log
 out: Installation failed.

        at org.apache.tools.ant.ProjectHelper.addLocationToBuildException(ProjectHelper.java:551)
        at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:460)
        at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:119)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
        at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:390)
        at org.apache.tools.ant.Target.performTasks(Target.java:411)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1368)
        at org.formic.wizard.step.shared.InstallAction.execute(InstallAction.java:124)
        at org.formic.wizard.step.gui.InstallStep$1.run(InstallStep.java:162)
        at foxtrot.AbstractWorkerThread$1.run(AbstractWorkerThread.java:40)
        at java.security.AccessController.doPrivileged(Native Method)
        at foxtrot.AbstractWorkerThread.runTask(AbstractWorkerThread.java:36)
        at foxtrot.workers.SingleWorkerThread.run(SingleWorkerThread.java:199)
        at foxtrot.workers.SingleWorkerThread.run(SingleWorkerThread.java:182)
        at java.lang.Thread.run(Thread.java:745)
Caused by: jar:file:/home/hinmanm/Downloads/eclim_2.5.0.jar!/installer.xml:326: error: The installable unit org.eclim.feature.group has not been found.
Application failed, log file location: /home/hinmanm/.eclipse/org.eclipse.platform_793567567_linux_gtk_x86_64/configuration/1441737738576.log
 out: Installation failed.

        at org.eclim.installer.ant.UninstallIUTask.runCommand(UninstallIUTask.java:161)
        at org.eclim.installer.ant.UninstallIUTask.execute(UninstallIUTask.java:83)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
        at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
        at net.sf.antcontrib.logic.IfTask.execute(IfTask.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.TaskAdapter.execute(TaskAdapter.java:154)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
        at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:390)
        at org.apache.tools.ant.Target.performTasks(Target.java:411)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
        at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
        at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:458)
        ... 19 more
Caused by: error: The installable unit org.eclim.feature.group has not been found.
Application failed, log file location: /home/hinmanm/.eclipse/org.eclipse.platform_793567567_linux_gtk_x86_64/configuration/1441737738576.log
 out: Installation failed.

        at org.eclim.installer.ant.UninstallIUTask.runCommand(UninstallIUTask.java:154)
        ... 46 more
Installer Context (Please include in bug reports):
  eclipse.home=/usr/lib64/eclipse
  eclipse.info=org.eclim.installer.step.EclipseInfo@1089b8ef
  eclipse.local=/home/hinmanm/.eclipse/org.eclipse.platform_793567567_linux_gtk_x86_64
  eclipse.profile=SDKProfile
  featureList.adt=false
  featureList.cdt=false
  featureList.dltk=false
  featureList.dltkruby=false
  featureList.groovy=false
  featureList.jdt=true
  featureList.pdt=false
  featureList.pydev=false
  featureList.sdt=false
  featureList.wst=false
  vim.skip=true
2015-09-08 12:42:42,702 INFO  [org.formic.Installer] Installer Finished.
2015-09-08 12:42:42,703 DEBUG [ANT]
BUILD SUCCESSFUL
Total time: 47 seconds
2015-09-08 12:42:42,708 WARN  [ANT]      [echo] Installation canceled.
2015-09-08 12:42:42,722 WARN  [ANT]      [echo]
2015-09-08 12:42:42,722 WARN  [ANT]      [echo] ##
2015-09-08 12:42:42,722 WARN  [ANT]      [echo] # Please wait while the eclim installer feature is removed from eclipse...
2015-09-08 12:42:42,722 WARN  [ANT]      [echo] ##
2015-09-08 12:42:42,722 WARN  [ANT]      [echo]
2015-09-08 12:42:42,723 INFO  [ANT] [eclim:uninstalliu] Uninstalling org.eclim.installer...
2015-09-08 12:42:42,723 INFO  [org.formic.util.CommandExecutor] java -Xmx256m -XX:MaxPermSize=128m -jar /usr/lib64/eclipse/plugins/org.eclipse.equinox.launcher_1.3.100.v20150826-1000.jar -clean -application org.eclipse.equinox.p2.director -repository file:///tmp/formic_273611395/update -uninstallIU org.eclim.installer.feature.group
2015-09-08 12:42:45,836 INFO  [org.eclim.installer.ant.UninstallIUTask] Uninstalling org.eclim.installer.feature.group 2.5.0.
2015-09-08 12:42:47,282 INFO  [org.eclim.installer.ant.UninstallIUTask] Operation completed in 1455 ms.
2015-09-08 12:42:47,557 INFO  [ANT] [eclim:uninstalliu] Invoking p2 gc...
2015-09-08 12:42:47,557 INFO  [org.formic.util.CommandExecutor] java -Xmx256m -XX:MaxPermSize=128m -jar /usr/lib64/eclipse/plugins/org.eclipse.equinox.launcher_1.3.100.v20150826-1000.jar -clean -application org.eclipse.equinox.p2.garbagecollector.application -profile SDKProfile
2015-09-08 12:42:51,709 INFO  [org.eclim.installer.ant.UninstallIUTask] Removing temp repositories from p2 prefs: /home/hinmanm/.eclipse/org.eclipse.platform_793567567_linux_gtk_x86_64/p2/org.eclipse.equinox.p2.engine/profileRegistry/SDKProfile.profile/.data/.settings/org.eclipse.equinox.p2.metadata.repository.prefs
2015-09-08 12:42:51,712 INFO  [ANT]      [move] Moving 1 file to /home/hinmanm/.eclipse/org.eclipse.platform_793567567_linux_gtk_x86_64/p2/org.eclipse.equinox.p2.engine/profileRegistry/SDKProfile.profile/.data/.settings
PATH=/opt/jdk1.7.0_79/bin:$PATH JAVA_HOME=/opt/jdk1.7.0_79 java -jar   56.12s user 0.92s system 100% cpu 56.767 total
```

This is for Eclipse Mars on Fedora Linux with eclim 2.5.0

**Comment by ervandew** [comment]
Looks like maybe you had previously installed eclim from source and the installer is trying to remove it, but the eclipse provisioning tool can't find it. You may have to manually remove any existing eclim files from your eclipse install or start over with a clean eclipse install.

**Comment by dakrone** [comment]
@ervandew that was it, I had to manually remove all the previous eclim things before I was able to re-install the new version. Thanks!

**Comment by emmanueltouzery** [comment]
I am having the same problem. Which files should I delete? My `eclipse` is the system one, nothing got written there, only root can (it's in `/usr/lib64/eclipse`). I tried deleting things containing the `eclim` word from ~/.eclipse but to no avail.

**Comment by emmanueltouzery** [comment]
I've also deleted things under `features` now, and now getting:

    Caused by:  java.io.FileNotFoundException: /home/emmanuel/.eclipse/org.eclipse.platform_793567567_linux_gtk_x86_64/features/org.eclim_2.5.0 (No such file or directory)
