### ISSUE TITLE
Can't start eclimd after install on Debian/JDK 1.7 x64

### ISSUE THREAD

**Issue by badbob** [ervandew/eclim#444]
$:~/eclipse/mars$ ./eclimd
/usr/lib/jvm/default-java/bin/java -version
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)

/usr/lib/jvm/default-java/bin/java -d64 -Dosgi.requiredJavaVersion=1.7 -XX:MaxPermSize=256m -Xms256m -Xmx1024m -jar /home/user/eclipse/mars/plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar --launcher.suppressErrors -debug -clean -refresh -application org.eclim.application
Install location:
    file:/home/user/eclipse/mars/
Configuration file:
    file:/home/user/eclipse/mars/configuration/config.ini loaded
Configuration location:
    file:/home/user/eclipse/mars/configuration/
Framework located:
    file:/home/user/eclipse/mars/plugins/org.eclipse.osgi_3.10.101.v20150820-1432.jar
Loading extension: reference:file:org.eclipse.osgi.compatibility.state_1.0.100.v20150402-1551.jar
        eclipse.properties not found
Framework classpath:
    file:/home/user/eclipse/mars/plugins/org.eclipse.osgi_3.10.101.v20150820-1432.jar
    file:/home/user/eclipse/mars/plugins/
    file:/home/user/eclipse/mars/plugins/org.eclipse.osgi.compatibility.state_1.0.100.v20150402-1551.jar
Debug options:
    file:/home/user/eclipse/mars/.options not found
Time to load bundles: 76
org.eclipse.m2e.logback.configuration: The org.eclipse.m2e.logback.configuration bundle was activated before the state location was initialized.  Will retry after the state location is initialized.
Starting application: 20285
org.eclipse.m2e.logback.configuration: Logback config file: /home/user/workspace/.metadata/.plugins/org.eclipse.m2e.logback.configuration/logback.1.6.2.20150902-0002.xml
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [bundleresource://914.fwk167083497:1/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [bundleresource://914.fwk167083497:2/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
org.eclipse.m2e.logback.configuration: Initializing logback
An error has occurred. See the log file
/home/screw/workspace/.metadata/.log.
Exception in thread "Thread-4" java.lang.NoClassDefFoundError: org/eclipse/ui/PlatformUI
        at org.eclim.eclipse.EclimApplication.shutdown(EclimApplication.java:144)
        at org.eclim.eclipse.EclimApplication$1.run(EclimApplication.java:102)
Caused by: java.lang.ClassNotFoundException: org.eclipse.ui.PlatformUI cannot be found by org.eclim_2.5.0
        at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:439)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:352)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:344)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 2 more
'''

**Comment by badbob** [comment]
```
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=ru_RU
Framework arguments:  --launcher.suppressErrors -refresh -application org.eclim.application
Command-line arguments:  --launcher.suppressErrors -debug -clean -refresh -application org.eclim.application

!ENTRY org.eclipse.osgi 4 0 2015-12-13 20:08:47.968
!MESSAGE Application error
!STACK 1
java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons:
        /home/user/eclipse/mars/configuration/org.eclipse.osgi/753/0/.cp/libswt-pi-gtk-4528.so: libgtk-x11-2.0.so.0: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога
        no swt-pi-gtk in java.library.path
        /home/user/.swt/lib/linux/x86_64/libswt-pi-gtk-4528.so: libgtk-x11-2.0.so.0: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога
        Can't load library: /home/user/.swt/lib/linux/x86_64/libswt-pi-gtk.so

        at org.eclipse.swt.internal.Library.loadLibrary(Library.java:327)
        at org.eclipse.swt.internal.Library.loadLibrary(Library.java:236)
        at org.eclipse.swt.internal.gtk.OS.<clinit>(OS.java:44)
        at org.eclipse.swt.internal.Converter.wcsToMbcs(Converter.java:63)
        at org.eclipse.swt.internal.Converter.wcsToMbcs(Converter.java:54)
        at org.eclipse.swt.widgets.Display.<clinit>(Display.java:134)
        at org.eclipse.ui.internal.Workbench.createDisplay(Workbench.java:734)
        at org.eclipse.ui.PlatformUI.createDisplay(PlatformUI.java:162)
        at org.eclipse.ui.internal.ide.application.IDEApplication.createDisplay(IDEApplication.java:169)
        at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:111)
        at org.eclim.eclipse.EclimApplication.start(EclimApplication.java:128)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
(END)

```

**Comment by ervandew** [comment]
Can you start the eclipse gui?  Are you running on a headless server?

**Comment by badbob** [comment]
Hi, ervandew. 
I solved the issue. 

This (described) error was about inconsistency about some packages architecture. Looks like some of packages installed on my computer has 32-bit arch. 

More details on Stackoverflow: http://stackoverflow.com/questions/10165693

After installing 32-bit JDK and 32-bit Eclipse, I get another error:

```
BootLoader constants: OS=linux, ARCH=x86, WS=gtk, NL=ru_RU
Framework arguments:  --launcher.suppressErrors -refresh -application org.eclim.application
Command-line arguments:  --launcher.suppressErrors -debug -clean -refresh -application org.eclim.application

!ENTRY org.eclipse.osgi 4 0 2015-12-13 20:32:34.717
!MESSAGE Application error
!STACK 1
org.eclipse.swt.SWTError: No more handles [gtk_init_check() failed]
        at org.eclipse.swt.SWT.error(SWT.java:4517)
        at org.eclipse.swt.widgets.Display.createDisplay(Display.java:908)
        at org.eclipse.swt.widgets.Display.create(Display.java:892)
        at org.eclipse.swt.graphics.Device.<init>(Device.java:156)
        at org.eclipse.swt.widgets.Display.<init>(Display.java:512)
        at org.eclipse.swt.widgets.Display.<init>(Display.java:503)
        at org.eclipse.ui.internal.Workbench.createDisplay(Workbench.java:750)
        at org.eclipse.ui.PlatformUI.createDisplay(PlatformUI.java:162)
        at org.eclipse.ui.internal.ide.application.IDEApplication.createDisplay(IDEApplication.java:169)
        at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:111)
        at org.eclim.eclipse.EclimApplication.start(EclimApplication.java:128)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1488)

```

This error described here: http://unix.stackexchange.com/questions/94497/
I just tried to run vim in Putty without X11-forwarding. 
Is there any way to run eclim without any X11 references?

**Comment by ervandew** [comment]
> Is there any way to run eclim without any X11 references?

On a headless server you can use xvfb in place of a full x server.

There's an example here: http://eclim.org/install.html#install-headless

**Comment by greenglass** [comment]
I am running into this same issue, since I would rather not install 32-bit Java/Eclipse I can help get to the root of this issue.

Setup:
```
Linux version 4.0.4-301.fc22.x86_64 (mockbuild@bkernel02.phx2.fedoraproject.org) (gcc version 5.1.1 20150422 (Red Hat 5.1.1-1) (GCC) ) #1 SMP Thu May 21 13:10:33 UTC 2015

[vagrant@localhost ~]$ cat /etc/*release*
Fedora release 22 (Twenty Two)
NAME=Fedora
VERSION="22 (Twenty Two)"
ID=fedora
VERSION_ID=22
PRETTY_NAME="Fedora 22 (Twenty Two)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:22"
HOME_URL="https://fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=22
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=22
PRIVACY_POLICY_URL=https://fedoraproject.org/wiki/Legal:PrivacyPolicy
Fedora release 22 (Twenty Two)
Fedora release 22 (Twenty Two)
cpe:/o:fedoraproject:fedora:22
```

Output from following instructions on using a headless server.
```
[vagrant@localhost ~]$ Xvfb :1 -screen 0 1024x768x24 &
[1] 4256
[vagrant@localhost ~]$ DISPLAY=:1 ./eclipse/eclimd -b
[vagrant@localhost ~]$ OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [bundleresource://914.fwk13326370:1/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [bundleresource://914.fwk13326370:2/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
Exception in thread "Thread-4" java.lang.NoClassDefFoundError: org/eclipse/ui/PlatformUI
        at org.eclim.eclipse.EclimApplication.shutdown(EclimApplication.java:144)
        at org.eclim.eclipse.EclimApplication$1.run(EclimApplication.java:102)
Caused by: java.lang.ClassNotFoundException: org.eclipse.ui.PlatformUI cannot be found by org.eclim_2.5.0
        at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:439)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:352)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:344)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 2 more
```

```
!SESSION 2016-02-07 19:07:21.988 -----------------------------------------------
eclipse.buildId=4.5.1.M20150904-0015
java.version=1.8.0_71
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  --launcher.suppressErrors -refresh -application org.eclim.application
Command-line arguments:  --launcher.suppressErrors -debug -clean -refresh -application org.eclim.application

!ENTRY org.eclipse.osgi 4 0 2016-02-07 19:07:45.006
!MESSAGE Application error
!STACK 1
java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons:
        /home/vagrant/eclipse/configuration/org.eclipse.osgi/753/0/.cp/libswt-pi-gtk-4528.so: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
        no swt-pi-gtk in java.library.path
        /home/vagrant/.swt/lib/linux/x86_64/libswt-pi-gtk-4528.so: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
        Can't load library: /home/vagrant/.swt/lib/linux/x86_64/libswt-pi-gtk.so

        at org.eclipse.swt.internal.Library.loadLibrary(Library.java:327)
        at org.eclipse.swt.internal.Library.loadLibrary(Library.java:236)
        at org.eclipse.swt.internal.gtk.OS.<clinit>(OS.java:44)
        at org.eclipse.swt.internal.Converter.wcsToMbcs(Converter.java:63)
        at org.eclipse.swt.internal.Converter.wcsToMbcs(Converter.java:54)
        at org.eclipse.swt.widgets.Display.<clinit>(Display.java:134)
        at org.eclipse.ui.internal.Workbench.createDisplay(Workbench.java:734)
        at org.eclipse.ui.PlatformUI.createDisplay(PlatformUI.java:162)
        at org.eclipse.ui.internal.ide.application.IDEApplication.createDisplay(IDEApplication.java:169)
        at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:111)
        at org.eclim.eclipse.EclimApplication.start(EclimApplication.java:128)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
```

I have this currently working in a headless Ubuntu machine. Changing over to a Fedora vagrant box and can't get it working correctly. 

Any thoughts?

**Comment by tong-jomedia** [comment]
Any update on this issue I am running it in headless ubuntu machine too use jdk1.8 X 64 same issue

```
Configuration file:
    file:/home/vagrant/eclim/eclipse/configuration/config.ini loaded
Configuration location:
    file:/home/vagrant/eclim/eclipse/configuration/
Framework located:
    file:/home/vagrant/eclim/eclipse/plugins/org.eclipse.osgi_3.10.102.v20160118-1700.jar
Loading extension: reference:file:org.eclipse.osgi.compatibility.state_1.0.100.v20150402-1551.jar
        eclipse.properties not found
Framework classpath:
    file:/home/vagrant/eclim/eclipse/plugins/org.eclipse.osgi_3.10.102.v20160118-1700.jar
    file:/home/vagrant/eclim/eclipse/plugins/
    file:/home/vagrant/eclim/eclipse/plugins/org.eclipse.osgi.compatibility.state_1.0.100.v20150402-1551.jar
Debug options:
    file:/home/vagrant/eclim/eclipse/.options not found
Time to load bundles: 51
Starting application: 3383
An error has occurred. See the log file
/home/vagrant/workspace/.metadata/.log.
Exception in thread "Thread-3" java.lang.NoClassDefFoundError: org/eclipse/ui/PlatformUI
        at org.eclim.eclipse.EclimApplication.shutdown(EclimApplication.java:144)
        at org.eclim.eclipse.EclimApplication$1.run(EclimApplication.java:102)
Caused by: java.lang.ClassNotFoundException: org.eclipse.ui.PlatformUI cannot be found by org.eclim_2.5.0
        at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:439)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:352)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:344)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

```

**Comment by thisishantzz** [comment]
I too facing this issue. I am running a headless CentsOS 7 server and I keep getting this error.

```
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
Exception in thread "Thread-4" java.lang.NoClassDefFoundError: org/eclipse/ui/PlatformUI
        at org.eclim.eclipse.EclimApplication.shutdown(EclimApplication.java:144)
        at org.eclim.eclipse.EclimApplication$1.run(EclimApplication.java:102)
Caused by: java.lang.ClassNotFoundException: org.eclipse.ui.PlatformUI cannot be found by org.eclim_2.6.0
        at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:461)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:372)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:364)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:161)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 2 more
```
I tried using Eclipse Oxygen with eclim-2.7.0 and Eclipse Neon with eclim-2.6.0. I also tried using the jar files available on git as well as building eclim from source. I always get this error when I run eclimd using the command
`DISPLAY=:1 $ECLIPSE_HOME/eclimd -b`

**Comment by sw-fci-enablement-public** [comment]
I get the same error on Fedora 27 server, running headless.

**Comment by yunyouxi0** [comment]
> I get the same error on Fedora 27 server, running headless, VirtualBox, with terminal emulator of MobaXTerm for its X-11 forwarding (so I didn't use `Xvfb :1 -screen 0 1024x768x24 &` and `DISPLAY=:1 $ECLIPSE_HOME/eclimd -b`) .
> 
> Here was the error:
> 
> ```
> [x@eclim ~]$ ./eclipse/eclimd
> /usr/bin/java -version
> openjdk version "1.8.0_161"
> OpenJDK Runtime Environment (build 1.8.0_161-b14)
> OpenJDK 64-Bit Server VM (build 25.161-b14, mixed mode)
> JAVA_VERSION=8
> 
> /usr/bin/java -d64 -Dosgi.requiredJavaVersion=1.8 -Dosgi.instance.area.default=@user.home/eclipse-workspace -XX:+UseG1GC -Xms256m -Xmx1024m -jar /home/x/eclipse/plugins/org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar --launcher.suppressErrors -debug -clean -refresh -application org.eclim.application
> Install location:
>     file:/home/x/eclipse/
> Configuration file:
>     file:/home/x/eclipse/configuration/config.ini loaded
> Configuration location:
>     file:/home/x/eclipse/configuration/
> Framework located:
>     file:/home/x/eclipse/plugins/org.eclipse.osgi_3.12.50.v20170928-1321.jar
> Loading extension: reference:file:org.eclipse.osgi.compatibility.state_1.1.0.v20170516-1513.jar
>         eclipse.properties not found
> Framework classpath:
>     file:/home/x/eclipse/plugins/org.eclipse.osgi_3.12.50.v20170928-1321.jar
>     file:/home/x/eclipse/plugins/
>     file:/home/x/eclipse/plugins/org.eclipse.osgi.compatibility.state_1.1.0.v20170516-1513.jar
> Debug options:
>     file:/home/x/.options not found
> Time to load bundles: 75
> org.eclipse.m2e.logback.configuration: The org.eclipse.m2e.logback.configuration bundle was activated before the state location was initialized.  Will retry after the state location is initialized.
> Starting application: 10281
> org.eclipse.m2e.logback.configuration: Logback config file: /home/x/eclipse-workspace/.metadata/.plugins/org.eclipse.m2e.logback.configuration/logback.1.8.2.20171007-0217.xml
> SLF4J: Class path contains multiple SLF4J bindings.
> SLF4J: Found binding in [bundleresource://1037.fwk1476394199:1/org/slf4j/impl/StaticLoggerBinder.class]
> SLF4J: Found binding in [bundleresource://1037.fwk1476394199:2/org/slf4j/impl/StaticLoggerBinder.class]
> SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
> SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
> org.eclipse.m2e.logback.configuration: Initializing logback
> An error has occurred. See the log file
> /home/x/eclipse-workspace/.metadata/.log.
> Exception in thread "Thread-4" java.lang.NoClassDefFoundError: org/eclipse/ui/PlatformUI
>         at org.eclim.eclipse.EclimApplication.shutdown(EclimApplication.java:144)
>         at org.eclim.eclipse.EclimApplication$1.run(EclimApplication.java:102)
> Caused by: java.lang.ClassNotFoundException: org.eclipse.ui.PlatformUI cannot be found by org.eclim_2.7.2
>         at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:484)
>         at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395)
>         at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387)
>         at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
>         ... 2 more
> ```
> This fixed it for me (not sure if this is the "right" approach):
> 
> ```
> sudo dnf install -y gtk3-devel
> ./eclipse/eclimd
> ```

Work for me.
Thanks.
