### ISSUE TITLE
error while GUI install

### ISSUE THREAD

**Issue by zohaad** [ervandew/eclim#489]
jar:file:/home/zohaad/Downloads/eclim_2.6.0.jar!/installer.xml:145: The following error occurred while executing this line:
jar:file:/home/zohaad/Downloads/eclim_2.6.0.jar!/installer.xml:342: Directory does not exist: /home/zohaad/eclipse/features
        at org.apache.tools.ant.ProjectHelper.addLocationToBuildException(ProjectHelper.java:551)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:460)
	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:119)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:390)
	at org.apache.tools.ant.Target.performTasks(Target.java:411)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1368)
	at org.formic.wizard.step.shared.InstallAction.execute(InstallAction.java:124)
	at org.formic.wizard.step.gui.InstallStep$1.run(InstallStep.java:162)
	at foxtrot.AbstractWorkerThread$1.run(AbstractWorkerThread.java:40)
	at java.security.AccessController.doPrivileged(Native Method)
	at foxtrot.AbstractWorkerThread.runTask(AbstractWorkerThread.java:36)
	at foxtrot.workers.SingleWorkerThread.run(SingleWorkerThread.java:199)
	at foxtrot.workers.SingleWorkerThread.run(SingleWorkerThread.java:182)
	at java.lang.Thread.run(Thread.java:745)
Caused by: jar:file:/home/zohaad/Downloads/eclim_2.6.0.jar!/installer.xml:342: Directory does not exist: /home/zohaad/eclipse/features
	at org.apache.tools.ant.taskdefs.Delete.handle(Delete.java:704)
	at org.apache.tools.ant.taskdefs.Delete.execute(Delete.java:613)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:390)
	at org.apache.tools.ant.Target.performTasks(Target.java:411)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:458)
	... 19 more

**Comment by ervandew** [comment]
The eclim installer doesn't yet support the directory layout created when using the eclipse gui installer. Try using one of the .tar.gz eclipse distros instead.
