### ISSUE TITLE
cannot install eclim 2.6 on linux

### ISSUE THREAD

**Issue by paupalou** [ervandew/eclim#493]
Used tar.gz (just extract eclipse-jee-neon-1a-linux-gtk-x86_64.tar.gz ) last eclipse neon and eclim 2.6 , vim8 and java8.

Stacktrace:

`
!ENTRY org.eclipse.osgi 4 0 2016-11-30 11:00:16.051
!MESSAGE Application error
!STACK 1
java.lang.RuntimeException: Application "org.eclim.installer.application" could not be found in the registry. The applications available are: org.eclipse.ant.core.antRunner, org.eclipse.equinox.app.error, org.eclipse.equinox.p2.director, org.eclipse.equinox.p2.garbagecollector.application, org.eclipse.equinox.p2.publisher.InstallPublisher, org.eclipse.equinox.p2.publisher.EclipseGenerator, org.eclipse.equinox.p2.publisher.ProductPublisher, org.eclipse.equinox.p2.publisher.FeaturesAndBundlesPublisher, org.eclipse.equinox.p2.reconciler.application, org.eclipse.equinox.p2.repository.repo2runnable, org.eclipse.equinox.p2.repository.metadataverifier, org.eclipse.equinox.p2.artifact.repository.mirrorApplication, org.eclipse.equinox.p2.metadata.repository.mirrorApplication, org.eclipse.equinox.p2.touchpoint.natives.nativePackageExtractor, org.eclipse.equinox.p2.updatesite.UpdateSitePublisher, org.eclipse.equinox.p2.publisher.UpdateSitePublisher, org.eclipse.equinox.p2.publisher.CategoryPublisher, org.eclipse.oomph.setup.core.SetupArchiver, org.eclipse.pde.build.Build.
	at org.eclipse.equinox.internal.app.EclipseAppContainer.startDefaultApp(EclipseAppContainer.java:248)
	at org.eclipse.equinox.internal.app.MainApplicationLauncher.run(MainApplicationLauncher.java:29)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
`

Any clue ?

Thanks

**Comment by ervandew** [comment]
This typically indicates an issue with the eclipse install. I'd suggest:
1. make sure you extracted the new eclipse version to a new location and not on top of a previous install.
2. try moving your ~/.eclipse dir out of the way
3. try moving your default workspace out of the way

**Comment by paupalou** [comment]
Hey @ervandew , thanks for reply.

I have managed to make it work, the problem was JDK version, even i had installed jdk8 the default java bin (which java) pointed to jdk7, maybe this info is useful, so you can add a  "checker" for java version ;)

Regards
