### ISSUE TITLE
Installing eclim on Ubuntu 16.04 

### ISSUE THREAD

**Issue by nothingtwoit** [ervandew/eclim#507]
No luck installing Eclim, does anybody know what the error below means.
![screenshot from 2017-02-23 22-00-06](https://cloud.githubusercontent.com/assets/25716192/23292343/fc0f91bc-fa13-11e6-82cc-8dac28514970.png)
I have eclipse neon installed(the latest version).

**Comment by nothingtwoit** [comment]
jar:file:/home/nothing2it/Downloads/eclim_2.6.0.jar!/installer.xml:145: The following error occurred while executing this line:
jar:file:/home/nothing2it/Downloads/eclim_2.6.0.jar!/installer.xml:342: Directory does not exist: /home/nothing2it/eclipse/java-neon/eclipse/features
	at org.apache.tools.ant.ProjectHelper.addLocationToBuildException(ProjectHelper.java:551)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:460)
	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:119)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:390)

**Comment by calas** [comment]
Same problem here. Can not install eclim 2.6.0 in Ubuntu 16.04. 

First it won't correctly detect eclipse neon version then it fails when it's almost done installing. 

[install.log.txt](https://github.com/ervandew/eclim/files/821603/install.log.txt)

**Comment by gabrielps** [comment]
Try downloading the eclipse distribution and uncompressing where needed instead of using the installer. Also, I recommend to uncompress eclipse in a directory within your home.

Cheers :)

**Comment by calas** [comment]
Hello Gabriel, thanks for your answer. I tried that but it also failed, here is the log: 

[install.log.txt](https://github.com/ervandew/eclim/files/835986/install.log.txt)

**Comment by Capri-Sonne** [comment]
Same Error here i when i tried to install 2.6 version. Now i have tried to install the older one. Every thing work fine with (2.5) . 
Have a good day

**Comment by gabrielps** [comment]
@calas Im affraid i can't bring you a solution. Try @Capri-Sonne approach. So far, I can tell you everything is working fine, even the debugger.

**Comment by josiah14** [comment]
Easy workaround for me was just to create the features directory in the eclipse directory using the mkdir command.  Worked for me.

@gabrielps delete your features directory to reproduce this error.
