### ISSUE TITLE
Unable to find nature for alias 'java'.

### ISSUE THREAD

**Issue by gnh1201** [ervandew/eclim#526]
How to solve this problem? I can not find information about this error.

Command in vim
:ProjectCreate HelloWorld -n java

Error
Unable to find nature for alias 'java'.

> Application Started: 48480
> 2017-07-24 23:17:33,283 INFO  [org.eclim.eclipse.EclimDaemon] Workspace: /home/utilhome/eclipse-workspace
> 2017-07-24 23:17:33,310 INFO  [org.eclim.eclipse.EclimDaemon] Home: /home/utilhome/opt/eclipse/plugins/org.eclim_2.7.0/
> 2017-07-24 23:17:33,310 INFO  [org.eclim.eclipse.EclimDaemon] Starting eclim...
> 2017-07-24 23:17:33,320 INFO  [org.eclim.eclipse.EclimDaemon] Loading plugin org.eclim
> 2017-07-24 23:17:33,331 INFO  [org.eclim.eclipse.EclimDaemon] Loading plugin org.eclim.core
> 2017-07-24 23:17:33,532 INFO  [org.eclim.plugin.core.CorePlugin] Loading eclim plugins...
> 2017-07-24 23:17:33,569 INFO  [org.eclim.plugin.core.CorePlugin] Loading plugin org.eclim.jdt
> 2017-07-24 23:17:33,571 INFO  [org.eclim.plugin.core.CorePlugin] Loading plugin org.eclim.wst
> 2017-07-24 23:17:33,578 INFO  [org.eclim.plugin.core.CorePlugin] Plugins loaded.
> 2017-07-24 23:17:33,595 INFO  [org.eclim.eclipse.EclimDaemon] Loaded plugin org.eclim.core
> 2017-07-24 23:17:33,596 INFO  [org.eclim.eclipse.EclimDaemon] Waiting on running jobs before starting eclimd...
> 
> 2017-07-24 23:18:03,692 INFO  [org.eclim.eclipse.EclimDaemon] Eclim Server Started on: 127.0.0.1:9091
> 2017-07-24 23:19:19,624 ERROR [org.eclim.command.Main] Command failed
> java.lang.IllegalArgumentException: Unable to find nature for alias 'java'.  Supported aliases include: javascript=org.eclipse.wst.jsdt.core.jsNature
>         at org.eclim.plugin.core.project.ProjectManagement.create(ProjectManagement.java:156)
>         at org.eclim.plugin.core.command.project.ProjectCreateCommand.execute(ProjectCreateCommand.java:68)
>         at org.eclim.command.Main$1.run(Main.java:100)
>         at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:37)
>         at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
>         at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4497)
>         at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4110)
>         at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
>         at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
>         at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1044)
>         at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
>         at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
>         at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
>         at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
>         at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
>         at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
>         at org.eclim.eclipse.EclimApplication.start(EclimApplication.java:128)
>         at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
>         at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
>         at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
>         at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
>         at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.base/java.lang.reflect.Method.invoke(Method.java:564)
>         at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
>         at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
>         at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
>         at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
> NGSession 2: 127.0.0.1: org.eclim.command.Main exited with status 1
>

**Comment by Chinry** [comment]
I'm having a similar problem. If you've found a solution, please tell me.

**Comment by mightymicha** [comment]
Switching to jdk8 and reinstalling everything worked for me.

**Comment by Chinry** [comment]
Thank you, I edited my java version to be 8 and it worked.

**Comment by ervandew** [comment]
Yeah, looks like the eclipse jdt requires 1.8 to even load, so that must be the issue. I'll see about updating eclim accordingly.

**Comment by ervandew** [comment]
actually it seems I already have 1.8 requirements in the eclim plugins as well. Perhaps I just need to figure out how to validate that better.

**Comment by vincentwoo** [comment]
I'm having this issue running Oracle Java 10. Any word on this?
