### ISSUE TITLE
JavaDebugStatus fails

### ISSUE THREAD

**Issue by knut-soltvedt** [ervandew/eclim#528]
Hello,

I'm trying to use Eclim for debugging, still I'm not able to get it to work. I can attach Eclim to the (suspended) JVM via `JavaDebugStart`, but if a breakpoint is set the `JavaDebugStatus` returns me some error:
```
java.lang.ClassCastException: org.eclipse.jdt.internal.debug.core.logicalstructures.JDIReturnValueVariable cannot be cast to org.eclipse.jdt.internal.debug.core.model.JDIVariable
while executing command (port: 9091): -editor vim -command java_debug_status
```
When no breakpoint is set, the java program I try to debug is resumed directly when I attach Eclim to the JVM, so that I'm not able to set any breakpoint since the program ends before I can do anything. I guess that's the proper behaviour, though.

By the way, attaching a `jdb` to the JVM works proprely (breakpoints, and stepping are working).

I am using Eclim 2.7 and Eclipse 4.7.

Am I doing something wrong here?

Edit: I'm facing this problem even on simple hello world programs.

**Comment by clov0** [comment]
I'm having the same problem here.

* Vim : 8.0 (2016 Sep 12)
* Eclim : 4.7.0
* Eclim : 2.7.0 
* openjdk version "1.8.0_144"
* OpenJDK Runtime Environment (IcedTea 3.5.1) (suse-4.1-x86_64)
* OpenJDK 64-Bit Server VM (build 25.144-b01, mixed mode)

**Comment by arcseldon** [comment]
Seeing the same issue. Can set breakpoints / step - but cannot see status window. When I issue the command `:JavaDebugStatus`, then I get the above reported error.

**Comment by arcseldon** [comment]
`eclim 2.7.0`, `eclipse 4.7.1`, `java version "1.8.0_77"` running Mac 10.13.2

**Comment by arcseldon** [comment]
Ran `java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=1044 \
    -classpath ./bin org.test.debug.Main`

Then `mvn clean install tomcat7:run`

@ervandew - any ideas?  Everything is working great, just this debugger issue.

**Comment by arcseldon** [comment]
Do see port `9091` in use:

```
lsof -i :9091
COMMAND   PID      USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
java    61462 myusername   68u  IPv6 0x8a8376a841be79d7      0t0  TCP localhost:xmltec-xmlmail (LISTEN)
```

**Comment by arcseldon** [comment]
Am running remote debug against tomcat, but was able to produce this error somehow too:

```
java.lang.RuntimeException: Requird settings 'org.eclim.java.run.mainclass' has not been set.
while executing command (port: 9091): -editor vim -command java -p "my-project-name"
```

Not clear how i did that, as now unable to determine how to reproduce. Is it even relevant given am debugging web app, not a java app with a main method?

**Comment by arcseldon** [comment]
Final message - can add breakpoints, step, resume threads etc - just cannot see any status so renders this useless.

**Comment by arcseldon** [comment]
@dudinea - did your "fix" above get merged into master? or is outstanding PR etc?

**Comment by arcseldon** [comment]
From `eclim` server running on command line, here is the stack trace(s):

```
2018-01-01 18:32:06,729 INFO  [org.eclim.eclipse.EclimDaemon] Eclim Server Started on: 127.0.0.1:9091
2018-01-02 12:08:23,809 INFO  [org.eclim.plugin.jdt.command.debug.context.DebuggerContext] Starting debug session at localhost:8000 for vim instance: DEBUG
2018-01-02 12:11:22,573 ERROR [org.eclim.plugin.jdt.command.debug.event.DebugEventSetListener] Listener failed
java.lang.ClassCastException: org.eclipse.jdt.internal.debug.core.logicalstructures.JDIReturnValueVariable cannot be cast to org.eclipse.jdt.internal.debug.core.model.JDIVariable
	at org.eclim.plugin.jdt.command.debug.ui.VariableView.process(VariableView.java:224)
	at org.eclim.plugin.jdt.command.debug.ui.VariableView.get(VariableView.java:147)
	at org.eclim.plugin.jdt.command.debug.event.ThreadEventHandler.handle(ThreadEventHandler.java:84)
	at org.eclim.plugin.jdt.command.debug.event.DebugEventSetListener.handleDebugEvents(DebugEventSetListener.java:66)
	at org.eclipse.debug.core.DebugPlugin$EventNotifier.run(DebugPlugin.java:1155)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.debug.core.DebugPlugin$EventNotifier.dispatch(DebugPlugin.java:1189)
	at org.eclipse.debug.core.DebugPlugin$EventDispatchJob.run(DebugPlugin.java:442)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
2018-01-02 12:12:57,214 ERROR [org.eclim.plugin.jdt.command.debug.event.DebugEventSetListener] Listener failed
java.lang.ClassCastException: org.eclipse.jdt.internal.debug.core.logicalstructures.JDIReturnValueVariable cannot be cast to org.eclipse.jdt.internal.debug.core.model.JDIVariable
	at org.eclim.plugin.jdt.command.debug.ui.VariableView.process(VariableView.java:224)
	at org.eclim.plugin.jdt.command.debug.ui.VariableView.get(VariableView.java:147)
	at org.eclim.plugin.jdt.command.debug.event.ThreadEventHandler.handle(ThreadEventHandler.java:84)
	at org.eclim.plugin.jdt.command.debug.event.DebugEventSetListener.handleDebugEvents(DebugEventSetListener.java:66)
	at org.eclipse.debug.core.DebugPlugin$EventNotifier.run(DebugPlugin.java:1155)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.debug.core.DebugPlugin$EventNotifier.dispatch(DebugPlugin.java:1189)
	at org.eclipse.debug.core.DebugPlugin$EventDispatchJob.run(DebugPlugin.java:442)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
2018-01-02 12:25:58,028 ERROR [org.eclim.command.Main] Command failed
java.lang.ClassCastException: org.eclipse.jdt.internal.debug.core.logicalstructures.JDIReturnValueVariable cannot be cast to org.eclipse.jdt.internal.debug.core.model.JDIVariable
	at org.eclim.plugin.jdt.command.debug.ui.VariableView.process(VariableView.java:224)
	at org.eclim.plugin.jdt.command.debug.ui.VariableView.get(VariableView.java:147)
	at org.eclim.plugin.jdt.command.debug.context.DebuggerContext.getStatus(DebuggerContext.java:232)
	at org.eclim.plugin.jdt.command.debug.DebugStatusCommand.execute(DebugStatusCommand.java:43)
	at org.eclim.command.Main$1.run(Main.java:100)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:37)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4033)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3700)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at org.eclim.eclipse.EclimApplication.start(EclimApplication.java:128)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
NGSession 2: 127.0.0.1: org.eclim.command.Main exited with status 1
```

**Comment by ervandew** [comment]
@arcseldon 
A little while ago I released eclim 2.7.1 which includes the fix from @dudinea (#529).

**Comment by arcseldon** [comment]
@ervandew - thank you very much for this info. I shall try that version and report here.

**Comment by arcseldon** [comment]
@ervandew - Excellent, all working as expected with 2.7.1
