### ISSUE TITLE
Headless installation fails with multiple error messages (NullPointerException, source file doesn't exist)

### ISSUE THREAD

**Issue by cpitclaudel** [ervandew/eclim#541]
I'm trying to setup eclim on a Raspbian system.  I'm using Debian's eclipse package, because eclipse.org doesn't seem to supply ARM packages.

There's no X server on the machine, so I'm running a headless install.  My eclipse home is in `/usr/lib/eclipse/`, which isn't world-writable, which I think is the likely reason why the failures below occur:

```
user@raspi:~/eclim$ java -Dvim.skip=true -Declipse.home="/usr/lib/eclipse/" -jar eclim_2.7.0.jar install
Buildfile: installer.xml
2017-10-23 13:23:53,437 INFO  [ANT] [eclim:unattended] Installing eclim installer feature (may take a few moments).
2017-10-23 13:23:53,828 INFO  [org.formic.util.CommandExecutor] java -Xmx256m -jar /usr/lib/eclipse/plugins/org.eclipse.equinox.launcher_1.3.0.dist.jar -clean -application org.eclipse.equinox.p2.director -repository file:///tmp/formic_90506857/update -installIU org.eclim.installer.feature.group
2017-10-23 13:37:24,236 INFO  [ANT] [eclim:unattended] Analyzing installed features...
2017-10-23 13:37:24,269 INFO  [org.formic.util.CommandExecutor] java -Xmx256m -jar /usr/lib/eclipse/plugins/org.eclipse.equinox.launcher_1.3.0.dist.jar -clean -application org.eclim.installer.application -info
2017-10-23 13:44:05,543 INFO  [org.eclim.installer.step.EclipseInfo]   Profile: PlatformProfile
2017-10-23 13:44:05,570 INFO  [org.eclim.installer.step.EclipseInfo] eclipse.profile=PlatformProfile
2017-10-23 13:44:05,573 INFO  [org.eclim.installer.step.EclipseInfo]   Configuration: file:/home/user/.eclipse/org.eclipse.platform_3.8_155965261/configuration/
2017-10-23 13:44:05,574 INFO  [org.eclim.installer.step.EclipseInfo] eclipse.local=/home/user/.eclipse/org.eclipse.platform_3.8_155965261
2017-10-23 13:44:05,602 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.sdk 3.8.1.dist-7Q85DOBoMDElVYJXaEcz0e0aY6Tnt0Ra0eDROJ9IBeOgk file:/usr/lib/eclipse/dropins/sdk/
2017-10-23 13:44:05,624 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.pde 3.8.1.dist-7c7vFiyFALX8A file:/usr/lib/eclipse/dropins/sdk/
2017-10-23 13:44:05,627 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.help 1.4.1.dist-8v7oFRvFCmSPZkILLj597H file:/usr/lib/eclipse/
2017-10-23 13:44:05,631 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.platform 3.8.1.dist-A8F8_IVSG4VZSDmg7oLVfBs5JohYFyJZcMPL9 file:/usr/lib/eclipse/
2017-10-23 13:44:05,635 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.rcp 3.8.1.dist-8LA2GODFTJUDJ21934 file:/usr/lib/eclipse/
2017-10-23 13:44:05,638 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.cvs 1.3.200.dist-7B79FJJ9exZ_ file:/usr/lib/eclipse/
2017-10-23 13:44:05,641 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclipse.jdt 3.8.1.dist-8-8nFqrFFgQGJ file:/usr/share/eclipse/dropins/jdt/
2017-10-23 13:44:05,644 INFO  [org.eclim.installer.step.EclipseInfo]   Feature: org.eclim.installer 2.7.0 file:/home/user/.eclipse/org.eclipse.platform_3.8_155965261/
2017-10-23 13:44:24,561 INFO  [ANT] [eclim:unattended] Finished analyzing your eclipse installation.
2017-10-23 13:44:24,592 INFO  [ANT] [eclim:unattended] Eclim features to be installed:
2017-10-23 13:44:24,594 INFO  [ANT] [eclim:unattended]   jdt
2017-10-23 13:44:25,277 INFO  [ANT] [eclim:shutdown] Unable to shut down eclimd (9091): java.lang.NullPointerException - null
2017-10-23 13:44:26,183 INFO  [ANT]      [exec] rm: cannot remove '/home/user/.eclipse/org.eclipse.platform_3.8_155965261/eclim': No such file or directory
2017-10-23 13:44:26,601 ERROR [ANT]      [exec] Result: 1
2017-10-23 13:44:26,712 INFO  [ANT]      [exec] rm: cannot remove '/home/user/.eclipse/org.eclipse.platform_3.8_155965261/eclimd': No such file or directory
2017-10-23 13:44:27,014 ERROR [ANT]      [exec] Result: 1
2017-10-23 13:44:29,422 INFO  [ANT]     [mkdir] Created dir: /tmp/formic_90506857/update-site/plugins
2017-10-23 13:44:29,429 INFO  [ANT]     [mkdir] Created dir: /tmp/formic_90506857/update-site/features
2017-10-23 13:44:30,074 INFO  [ANT] [eclim:unzip] Expanding: /tmp/eclim-update-site3050122116859723891.zip into /tmp/formic_90506857/update-site
2017-10-23 13:44:36,145 INFO  [ANT] [formic:template] Evaluating template: /tmp/formic_90506857/update-site/artifacts.xml
2017-10-23 13:44:36,424 INFO  [ANT] [formic:template] Moving 1 file to /tmp/formic_90506857/update-site
2017-10-23 13:44:36,446 INFO  [ANT] [formic:template] Evaluating template: /tmp/formic_90506857/update-site/content.xml
2017-10-23 13:44:36,713 INFO  [ANT] [formic:template] Moving 1 file to /tmp/formic_90506857/update-site
2017-10-23 13:44:36,739 INFO  [ANT] [formic:template] Evaluating template: /tmp/formic_90506857/update-site/features/org.eclim_2.7.0/feature.xml
2017-10-23 13:44:36,790 INFO  [ANT] [formic:template] Moving 1 file to /tmp/formic_90506857/update-site/features/org.eclim_2.7.0
2017-10-23 13:44:37,356 INFO  [ANT]       [jar] Building jar: /tmp/formic_90506857/update-site/artifacts.jar
2017-10-23 13:44:37,421 INFO  [ANT]    [delete] Deleting: /tmp/formic_90506857/update-site/artifacts.xml
2017-10-23 13:44:37,514 INFO  [ANT]       [jar] Building jar: /tmp/formic_90506857/update-site/content.jar
2017-10-23 13:44:37,549 INFO  [ANT]    [delete] Deleting: /tmp/formic_90506857/update-site/content.xml
2017-10-23 13:44:37,711 INFO  [ANT]       [jar] Building jar: /tmp/formic_90506857/update-site/features/org.eclim_2.7.0.jar
2017-10-23 13:44:37,818 INFO  [ANT]    [delete] Deleting directory /tmp/formic_90506857/update-site/features/org.eclim_2.7.0
2017-10-23 13:44:38,031 INFO  [ANT]       [jar] Building jar: /tmp/formic_90506857/update-site/plugins/org.eclim.core_2.7.0.jar
2017-10-23 13:44:42,126 INFO  [ANT]    [delete] Deleting directory /tmp/formic_90506857/update-site/plugins/org.eclim.core_2.7.0
2017-10-23 13:44:42,449 INFO  [ANT]       [jar] Building jar: /tmp/formic_90506857/update-site/plugins/org.eclim.jdt_2.7.0.jar
2017-10-23 13:44:44,416 INFO  [ANT]    [delete] Deleting directory /tmp/formic_90506857/update-site/plugins/org.eclim.jdt_2.7.0
2017-10-23 13:44:44,744 INFO  [ANT]       [jar] Building jar: /tmp/formic_90506857/update-site/plugins/org.eclim.vimplugin_2.7.0.jar
2017-10-23 13:44:45,870 INFO  [ANT]    [delete] Deleting directory /tmp/formic_90506857/update-site/plugins/org.eclim.vimplugin_2.7.0
2017-10-23 13:44:46,455 INFO  [ANT]       [jar] Building jar: /tmp/formic_90506857/update-site/plugins/org.eclim_2.7.0.jar
2017-10-23 13:44:50,792 INFO  [ANT]    [delete] Deleting directory /tmp/formic_90506857/update-site/plugins/org.eclim_2.7.0
2017-10-23 13:44:50,878 INFO  [ANT] [eclim:installiu] Installing org.eclim...
2017-10-23 13:44:50,906 INFO  [org.formic.util.CommandExecutor] java -Xmx256m -jar /usr/lib/eclipse/plugins/org.eclipse.equinox.launcher_1.3.0.dist.jar -clean -application org.eclipse.equinox.p2.director -repository file:///tmp/formic_90506857/update-site -installIU org.eclim.feature.group
2017-10-23 13:58:29,874 ERROR [ANT] 
jar:file:/home/user/eclim/eclim_2.7.0.jar!/installer.xml:231: Replace: source file /usr/lib/eclipse/plugins/org.eclim_2.7.0/bin/eclimd doesn't exist
	at org.apache.tools.ant.taskdefs.Replace.processFile(Replace.java:663)
	at org.apache.tools.ant.taskdefs.Replace.execute(Replace.java:538)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
	at net.sf.antcontrib.logic.IfTask.execute(IfTask.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.TaskAdapter.execute(TaskAdapter.java:154)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:390)
	at org.apache.tools.ant.Target.performTasks(Target.java:411)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:458)
	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:119)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:390)
	at org.apache.tools.ant.Target.performTasks(Target.java:411)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1368)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
	at org.formic.ant.Main.runBuild(Main.java:232)
	at org.formic.ant.Main.startAnt(Main.java:81)
	at org.formic.ant.Main.main(Main.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.simontuffs.onejar.Boot.run(Boot.java:306)
	at com.simontuffs.onejar.Boot.main(Boot.java:159)
2017-10-23 13:58:29,923 ERROR [ANT] 
jar:file:/home/user/eclim/eclim_2.7.0.jar!/installer.xml:146: The following error occurred while executing this line:
jar:file:/home/user/eclim/eclim_2.7.0.jar!/installer.xml:231: Replace: source file /usr/lib/eclipse/plugins/org.eclim_2.7.0/bin/eclimd doesn't exist
	at org.apache.tools.ant.ProjectHelper.addLocationToBuildException(ProjectHelper.java:551)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:460)
	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:119)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:390)
	at org.apache.tools.ant.Target.performTasks(Target.java:411)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1368)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
	at org.formic.ant.Main.runBuild(Main.java:232)
	at org.formic.ant.Main.startAnt(Main.java:81)
	at org.formic.ant.Main.main(Main.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.simontuffs.onejar.Boot.run(Boot.java:306)
	at com.simontuffs.onejar.Boot.main(Boot.java:159)
Caused by: jar:file:/home/user/eclim/eclim_2.7.0.jar!/installer.xml:231: Replace: source file /usr/lib/eclipse/plugins/org.eclim_2.7.0/bin/eclimd doesn't exist
	at org.apache.tools.ant.taskdefs.Replace.processFile(Replace.java:663)
	at org.apache.tools.ant.taskdefs.Replace.execute(Replace.java:538)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
	at net.sf.antcontrib.logic.IfTask.execute(IfTask.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.TaskAdapter.execute(TaskAdapter.java:154)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:390)
	at org.apache.tools.ant.Target.performTasks(Target.java:411)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:458)
	... 22 more
2017-10-23 13:58:29,986 DEBUG [ANT] 
BUILD SUCCESSFUL
Total time: 34 minutes 40 seconds
The following error occurred while executing this line:
jar:file:/home/user/eclim/eclim_2.7.0.jar!/installer.xml:231: Replace: source file /usr/lib/eclipse/plugins/org.eclim_2.7.0/bin/eclimd doesn't exist
```

Nonetheless, that `NullPointerException` doesn't look too encouraging.

I tried installing as root, but the installer bailed out early (`Running the eclim installer as root is highly discouraged.`).  What's the recommended way to install eclim on a Raspberry Pi?

Thanks!

**Comment by ervandew** [comment]
I just released a new command line installer for eclim. Give that a shot and let me know if that that works for you.

**Comment by cpitclaudel** [comment]
Thanks!  Looks great.  I won't be able to test until a few week from now, though, so I'll close now and reopen if I can reproduce the issue.
