### ISSUE TITLE
Formatter

### ISSUE THREAD

**Issue by smogstate** [ervandew/eclim#549]
Hi,
i am trying to format java code, i have installed google-java-formatter. I am using workspace formatting options

eclim log:

2017-12-21 11:04:35,503 INFO  [org.eclim.eclipse.EclimDaemon] Starting eclim...
2017-12-21 11:04:35,510 INFO  [org.eclim.eclipse.EclimDaemon] Loading plugin org.eclim
2017-12-21 11:04:35,512 INFO  [org.eclim.eclipse.EclimDaemon] Loading plugin org.eclim.core
2017-12-21 11:04:35,656 INFO  [org.eclim.plugin.core.CorePlugin] Loading eclim plugins...
2017-12-21 11:04:35,665 INFO  [org.eclim.plugin.core.CorePlugin] Loading plugin org.eclim.jdt
2017-12-21 11:04:35,667 INFO  [org.eclim.plugin.core.CorePlugin] Loading plugin org.eclim.wst
2017-12-21 11:04:35,671 INFO  [org.eclim.plugin.core.CorePlugin] Plugins loaded.
2017-12-21 11:04:35,671 INFO  [org.eclim.eclipse.EclimDaemon] Loaded plugin org.eclim.core
2017-12-21 11:04:35,672 INFO  [org.eclim.eclipse.EclimDaemon] Waiting on running jobs before starting eclimd...
2017-12-21 11:04:40,673 INFO  [org.eclim.eclipse.EclimDaemon] Jobs finished.
2017-12-21 11:04:40,674 INFO  [org.eclim.eclipse.EclimDaemon] Eclim Server Started on: 127.0.0.1:9091
2017-12-21 11:04:49,406 ERROR [org.eclim.command.Main] Command failed
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:422)
	at java.util.ArrayList.get(ArrayList.java:435)
	at org.eclipse.jdt.internal.formatter.TokenManager.get(TokenManager.java:73)
	at org.eclipse.jdt.internal.formatter.TokenManager.findIndex(TokenManager.java:166)
	at org.eclipse.jdt.internal.formatter.TokenManager.firstIndexBefore(TokenManager.java:221)
	at org.eclipse.jdt.internal.formatter.TokenManager.firstTokenBefore(TokenManager.java:225)
	at org.eclipse.jdt.internal.formatter.SpacePreparator.handleTokenBefore(SpacePreparator.java:1008)
	at org.eclipse.jdt.internal.formatter.SpacePreparator.handleCommas(SpacePreparator.java:993)
	at org.eclipse.jdt.internal.formatter.SpacePreparator.visit(SpacePreparator.java:277)
	at org.eclipse.jdt.core.dom.FieldDeclaration.accept0(FieldDeclaration.java:281)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2796)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2867)
	at org.eclipse.jdt.core.dom.TypeDeclaration.accept0(TypeDeclaration.java:470)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2796)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2867)
	at org.eclipse.jdt.core.dom.TypeDeclaration.accept0(TypeDeclaration.java:470)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2796)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2867)
	at org.eclipse.jdt.core.dom.CompilationUnit.accept0(CompilationUnit.java:257)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2796)
	at org.eclipse.jdt.internal.formatter.DefaultCodeFormatter.prepareSpaces(DefaultCodeFormatter.java:384)
	at org.eclipse.jdt.internal.formatter.DefaultCodeFormatter.prepareFormattedCode(DefaultCodeFormatter.java:220)
	at org.eclipse.jdt.internal.formatter.DefaultCodeFormatter.format(DefaultCodeFormatter.java:177)
	at org.eclipse.jdt.internal.formatter.DefaultCodeFormatter.format(DefaultCodeFormatter.java:160)
	at org.eclim.plugin.jdt.util.JavaUtils.format(JavaUtils.java:580)
	at org.eclim.plugin.jdt.command.src.FormatCommand.execute(FormatCommand.java:61)
	at org.eclim.command.Main$1.run(Main.java:100)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:37)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4497)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4110)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at org.eclim.eclipse.EclimApplication.start(EclimApplication.java:128)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
2017-12-21 11:05:03,523 ERROR [org.eclim.command.Main] Command failed
java.lang.ArrayIndexOutOfBoundsException

**Comment by ervandew** [comment]
Can you supply:
* your ecilpse version
* an example file that triggers the issue (ideally the smallest one possible that still produces the error)

**Comment by smogstate** [comment]
version=4.7.1

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.ToString;

import javax.persistence.Embeddable;

@Getter
@ToString
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode
@Builder
@Embeddable
public final class Address {

  private String country;

  private String zipCode;

  private String city;

    private String address1;

    private String address2;
}


Error:

2017-12-22 08:06:56,055 ERROR [org.eclim.command.Main] Command failed
java.lang.IndexOutOfBoundsException: Index: 90, Size: 90
        at java.util.ArrayList.rangeCheck(ArrayList.java:657)
        at java.util.ArrayList.get(ArrayList.java:433)
        at org.eclipse.jdt.internal.formatter.TokenManager.get(TokenManager.java:73)
        at org.eclipse.jdt.internal.formatter.TokenManager.findIndex(TokenManager.java:166)
        at org.eclipse.jdt.internal.formatter.SpacePreparator.handleEmptyParens(SpacePreparator.java:1042)
        at org.eclipse.jdt.internal.formatter.SpacePreparator.visit(SpacePreparator.java:210)
        at org.eclipse.jdt.core.dom.MethodDeclaration.accept0(MethodDeclaration.java:611)
        at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2796)
        at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2867)
        at org.eclipse.jdt.core.dom.TypeDeclaration.accept0(TypeDeclaration.java:470)
        at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2796)
        at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2867)
        at org.eclipse.jdt.core.dom.CompilationUnit.accept0(CompilationUnit.java:257)
        at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2796)
        at org.eclipse.jdt.internal.formatter.DefaultCodeFormatter.prepareSpaces(DefaultCodeFormatter.java:384)
        at org.eclipse.jdt.internal.formatter.DefaultCodeFormatter.prepareFormattedCode(DefaultCodeFormatter.java:220)
        at org.eclipse.jdt.internal.formatter.DefaultCodeFormatter.format(DefaultCodeFormatter.java:177)
        at org.eclipse.jdt.internal.formatter.DefaultCodeFormatter.format(DefaultCodeFormatter.java:160)
        at org.eclim.plugin.jdt.util.JavaUtils.format(JavaUtils.java:580)
        at org.eclim.plugin.jdt.command.src.FormatCommand.execute(FormatCommand.java:61)
        at org.eclim.command.Main$1.run(Main.java:100)
        at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:37)
        at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
        at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4497)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4110)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
        at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
        at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
        at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
        at org.eclim.eclipse.EclimApplication.start(EclimApplication.java:128)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1472)



On some classes i get just

2017-12-21 11:05:03,523 ERROR [org.eclim.command.Main] Command failed
java.lang.ArrayIndexOutOfBoundsException

**Comment by jamesdbowman** [comment]
I am also experiencing this issue on classes with the `@Builder` / `@Getter` / `@Setter` Lombok annotations.
