### ISSUE TITLE
openjdk 1.8.0_151: java.lang.NoClassDefFoundError: org/eclipse/ui/PlatformUI

### ISSUE THREAD

**Issue by Jim-Zenn** [ervandew/eclim#564]
I'm having this issue with `openjdk 1.8.0_151` and `eclipse 4.7.2`. FYI, I'm running an headless server.

```
/usr/bin/java -version
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)
JAVA_VERSION=8

/usr/bin/java -d64 -Dosgi.requiredJavaVersion=1.8 -Dosgi.instance.area.default=@user.home/eclipse-workspace -XX:+UseG1GC -Xms256m -Xmx1024m -jar /opt/eclipse/plugins/org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar --launcher.suppressErrors -debug -clean -refresh -application org.eclim.application
Install location:
    file:/opt/eclipse/
Configuration file:
    file:/opt/eclipse/configuration/config.ini loaded
Configuration location:
    file:/home/ubuntu/.eclipse/org.eclipse.platform_4.7.2_1473617060_linux_gtk_x86_64/configuration/
Configuration file:
    file:/home/ubuntu/.eclipse/org.eclipse.platform_4.7.2_1473617060_linux_gtk_x86_64/configuration/config.ini loaded
Loading timestamp file from:
         file:/home/ubuntu/.eclipse/org.eclipse.platform_4.7.2_1473617060_linux_gtk_x86_64/configuration/   .baseConfigIniTimestamp
Timestamps found:
         config.ini in the base: 1513586522000
         remembered 1513586522000
Shared configuration location:
    file:/opt/eclipse/configuration/
Framework located:
    file:/opt/eclipse/plugins/org.eclipse.osgi_3.12.50.v20170928-1321.jar
Loading extension: reference:file:org.eclipse.osgi.compatibility.state_1.1.0.v20170516-1513.jar
        eclipse.properties not found
Framework classpath:
    file:/opt/eclipse/plugins/org.eclipse.osgi_3.12.50.v20170928-1321.jar
    file:/opt/eclipse/plugins/
    file:/opt/eclipse/plugins/org.eclipse.osgi.compatibility.state_1.1.0.v20170516-1513.jar
Debug options:
    file:/home/ubuntu/.options not found
Time to load bundles: 107
org.eclipse.m2e.logback.configuration: The org.eclipse.m2e.logback.configuration bundle was activated before the state location was initialized.  Will retry after the state location is initialized.
Starting application: 13336
org.eclipse.m2e.logback.configuration: Logback config file: /home/ubuntu/eclipse-workspace/.metadata/.plugins/org.eclipse.m2e.logback.configuration/logback.1.8.2.20171007-0217.xml
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [bundleresource://500.fwk1596000437:1/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [bundleresource://500.fwk1596000437:2/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
org.eclipse.m2e.logback.configuration: Initializing logback
An error has occurred. See the log file
/home/ubuntu/eclipse-workspace/.metadata/.log.
Exception in thread "Thread-4" java.lang.NoClassDefFoundError: org/eclipse/ui/PlatformUI
        at org.eclim.eclipse.EclimApplication.shutdown(EclimApplication.java:144)
        at org.eclim.eclipse.EclimApplication$1.run(EclimApplication.java:102)
Caused by: java.lang.ClassNotFoundException: org.eclipse.ui.PlatformUI cannot be found by org.eclim_2.7.2
        at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:484)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 2 more
```

**Comment by zhonli** [comment]
export DISPLAY=:5
