### ISSUE TITLE
eclim_2.7.2 installer cannot locate Eclipse dependencies

### ISSUE THREAD

**Issue by JESii** [ervandew/eclim#579]
When attempting to install with one or more dependencies (e.g., 'Java Development', 'Ruby Development', etc.), the required dependencies could not be found:
```
dltkruby requires dltk, adding to selected
Eclim plugins to install:
  Java Development
  Web Development
  Ruby Development
  Groovy Development
Is this correct? (y/n): y

running: ['java', '-Djava.net.useSystemProxies=true', '-jar', '/Applications/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar', '-initialize', '-debug'] ... done
running: ['java', '-Djava.net.useSystemProxies=true', '-jar', '/Applications/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar', '-clean', '-refresh', '-application', 'org.eclipse.equinox.p2.garbagecollector.application'] ... done

Checking for required eclipse dependencies...
running: ['java', '-Djava.net.useSystemProxies=true', '-jar', '/Applications/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar', '-application', 'org.eclipse.equinox.p2.director', '-repository', u'http://download.eclipse.org/releases/oxygen/', '-list'] ... done

The following required dependencies could not be found:
  [*] org.codehaus.groovy.eclipse.feature not found.
  [*] org.codehaus.groovy.eclipse.feature not found.
  [*] org.codehaus.groovy.eclipse.feature not found.
  [*] org.codehaus.groovy.eclipse.feature not found.
```
I tried with various combinations or just one at a time -- all failed.
There are no proxies installed at this location.
When I tried with a DSL connection straight to the internet, it still failed.

Even if I request only 'Java Development', I get the following error:
```
The following required dependencies could not be found:
  [*] org.eclipse.jdt not found.
```
For completeness, here's the latest failure log:
```
!SESSION 2018-05-22 07:31:03.063 -----------------------------------------------
eclipse.buildId=4.7.3.M20180330-0640
java.version=1.8.0_171
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -application org.eclipse.equinox.p2.director -repository http://download.eclipse.org/releases/oxygen/ -list
Command-line arguments:  -application org.eclipse.equinox.p2.director -repository http://download.eclipse.org/releases/oxygen/ -list

!ENTRY org.eclipse.equinox.p2.core 4 0 2018-05-22 07:31:08.071
!MESSAGE Provisioning exception
!STACK 1
org.eclipse.equinox.p2.core.ProvisionException: Unable to read repository at http://download.eclipse.org/releases/oxygen/201803211000.
	at org.eclipse.equinox.internal.p2.metadata.repository.XZedSimpleMetadataRepositoryFactory.load(XZedSimpleMetadataRepositoryFactory.java:105)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.factoryLoad(MetadataRepositoryManager.java:57)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:768)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:668)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:96)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:92)
	at org.eclipse.equinox.internal.p2.metadata.repository.CompositeMetadataRepository.addChild(CompositeMetadataRepository.java:166)
	at org.eclipse.equinox.internal.p2.metadata.repository.CompositeMetadataRepository.<init>(CompositeMetadataRepository.java:106)
	at org.eclipse.equinox.internal.p2.metadata.repository.CompositeMetadataRepositoryFactory.load(CompositeMetadataRepositoryFactory.java:122)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.factoryLoad(MetadataRepositoryManager.java:57)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:768)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:668)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:96)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:92)
	at org.eclipse.equinox.internal.p2.director.app.DirectorApplication.getInstallableUnits(DirectorApplication.java:1219)
	at org.eclipse.equinox.internal.p2.director.app.DirectorApplication$LocationQueryable.query(DirectorApplication.java:90)
	at org.eclipse.equinox.p2.query.CompoundQueryable.getIteratorFromQueryable(CompoundQueryable.java:164)
	at org.eclipse.equinox.p2.query.CompoundQueryable.everything(CompoundQueryable.java:113)
	at org.eclipse.equinox.internal.p2.metadata.expression.RepeatableIterator$IndexProviderIterator.<init>(RepeatableIterator.java:129)
	at org.eclipse.equinox.internal.p2.metadata.expression.RepeatableIterator.create(RepeatableIterator.java:57)
	at org.eclipse.equinox.p2.query.ExpressionMatchQuery.perform(ExpressionMatchQuery.java:49)
	at org.eclipse.equinox.internal.p2.metadata.index.IndexProvider.query(IndexProvider.java:23)
	at org.eclipse.equinox.internal.p2.metadata.index.IndexProvider.query(IndexProvider.java:32)
	at org.eclipse.equinox.internal.p2.director.app.DirectorApplication.collectRootIUs(DirectorApplication.java:426)
	at org.eclipse.equinox.internal.p2.director.app.DirectorApplication.performList(DirectorApplication.java:760)
	at org.eclipse.equinox.internal.p2.director.app.DirectorApplication.run(DirectorApplication.java:1113)
	at org.eclipse.equinox.internal.p2.director.app.DirectorApplication.start(DirectorApplication.java:1293)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
Caused by: org.tukaani.xz.XZFormatException: Input is not in the XZ format
	at org.tukaani.xz.common.DecoderUtil.decodeStreamHeader(Unknown Source)
	at org.tukaani.xz.SingleXZInputStream.initialize(Unknown Source)
	at org.tukaani.xz.SingleXZInputStream.initialize(Unknown Source)
	at org.tukaani.xz.SingleXZInputStream.<init>(Unknown Source)
	at org.tukaani.xz.XZInputStream.<init>(Unknown Source)
	at org.tukaani.xz.XZInputStream.<init>(Unknown Source)
	at org.eclipse.equinox.internal.p2.metadata.repository.XZedSimpleMetadataRepositoryFactory.load(XZedSimpleMetadataRepositoryFactory.java:80)
	... 39 more
!SUBENTRY 1 org.eclipse.equinox.p2.metadata.repository 4 1002 2018-05-22 07:31:08.072
!MESSAGE Unable to read repository at http://download.eclipse.org/releases/oxygen/201803211000.
!STACK 0
org.tukaani.xz.XZFormatException: Input is not in the XZ format
	at org.tukaani.xz.common.DecoderUtil.decodeStreamHeader(Unknown Source)
	at org.tukaani.xz.SingleXZInputStream.initialize(Unknown Source)
	at org.tukaani.xz.SingleXZInputStream.initialize(Unknown Source)
	at org.tukaani.xz.SingleXZInputStream.<init>(Unknown Source)
	at org.tukaani.xz.XZInputStream.<init>(Unknown Source)
	at org.tukaani.xz.XZInputStream.<init>(Unknown Source)
	at org.eclipse.equinox.internal.p2.metadata.repository.XZedSimpleMetadataRepositoryFactory.load(XZedSimpleMetadataRepositoryFactory.java:80)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.factoryLoad(MetadataRepositoryManager.java:57)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:768)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:668)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:96)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:92)
	at org.eclipse.equinox.internal.p2.metadata.repository.CompositeMetadataRepository.addChild(CompositeMetadataRepository.java:166)
	at org.eclipse.equinox.internal.p2.metadata.repository.CompositeMetadataRepository.<init>(CompositeMetadataRepository.java:106)
	at org.eclipse.equinox.internal.p2.metadata.repository.CompositeMetadataRepositoryFactory.load(CompositeMetadataRepositoryFactory.java:122)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.factoryLoad(MetadataRepositoryManager.java:57)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:768)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:668)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:96)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:92)
	at org.eclipse.equinox.internal.p2.director.app.DirectorApplication.getInstallableUnits(DirectorApplication.java:1219)
	at org.eclipse.equinox.internal.p2.director.app.DirectorApplication$LocationQueryable.query(DirectorApplication.java:90)
	at org.eclipse.equinox.p2.query.CompoundQueryable.getIteratorFromQueryable(CompoundQueryable.java:164)
	at org.eclipse.equinox.p2.query.CompoundQueryable.everything(CompoundQueryable.java:113)
	at org.eclipse.equinox.internal.p2.metadata.expression.RepeatableIterator$IndexProviderIterator.<init>(RepeatableIterator.java:129)
	at org.eclipse.equinox.internal.p2.metadata.expression.RepeatableIterator.create(RepeatableIterator.java:57)
	at org.eclipse.equinox.p2.query.ExpressionMatchQuery.perform(ExpressionMatchQuery.java:49)
	at org.eclipse.equinox.internal.p2.metadata.index.IndexProvider.query(IndexProvider.java:23)
	at org.eclipse.equinox.internal.p2.metadata.index.IndexProvider.query(IndexProvider.java:32)
	at org.eclipse.equinox.internal.p2.director.app.DirectorApplication.collectRootIUs(DirectorApplication.java:426)
	at org.eclipse.equinox.internal.p2.director.app.DirectorApplication.performList(DirectorApplication.java:760)
	at org.eclipse.equinox.internal.p2.director.app.DirectorApplication.run(DirectorApplication.java:1113)
	at org.eclipse.equinox.internal.p2.director.app.DirectorApplication.start(DirectorApplication.java:1293)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
```

**Comment by JESii** [comment]
Just added the eclipse log to the issue

**Comment by ervandew** [comment]
Can you try manually running the command that eclim ran to lookup the
available eclipse plugins and see if it returns anything?

$ java \
    -Djava.net.useSystemProxies=true \
    -jar /Applications/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar \
    -application org.eclipse.equinox.p2.director \
    -repository http://download.eclipse.org/releases/oxygen/ \
    -list

On 2018-05-15 12:23:12, Jon Seidel wrote:
> When attempting to install with one or more dependencies (e.g., 'Java Development', 'Ruby Development', etc.), the required dependencies could not be found:
> ```
> dltkruby requires dltk, adding to selected
> Eclim plugins to install:
>   Java Development
>   Web Development
>   Ruby Development
>   Groovy Development
> Is this correct? (y/n): y
> 
> running: ['java', '-Djava.net.useSystemProxies=true', '-jar', '/Applications/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar', '-initialize', '-debug'] ... done
> running: ['java', '-Djava.net.useSystemProxies=true', '-jar', '/Applications/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar', '-clean', '-refresh', '-application', 'org.eclipse.equinox.p2.garbagecollector.application'] ... done
> 
> Checking for required eclipse dependencies...
> running: ['java', '-Djava.net.useSystemProxies=true', '-jar', '/Applications/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar', '-application', 'org.eclipse.equinox.p2.director', '-repository', u'http://download.eclipse.org/releases/oxygen/', '-list'] ... done
> 
> The following required dependencies could not be found:
>   [*] org.codehaus.groovy.eclipse.feature not found.
>   [*] org.codehaus.groovy.eclipse.feature not found.
>   [*] org.codehaus.groovy.eclipse.feature not found.
>   [*] org.codehaus.groovy.eclipse.feature not found.
> ```
> I tried with various combinations or just one at a time -- all failed.
> There are no proxies installed at this location.
> When I tried with a DSL connection straight to the internet, it still failed.
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ervandew/eclim/issues/579

-- 
eric

**Comment by ervandew** [comment]
Can you try manually running the command that eclim ran to lookup the available eclipse plugins and see if it returns anything?

    $ java \
        -Djava.net.useSystemProxies=true \
        -jar /Applications/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar \
        -application org.eclipse.equinox.p2.director \
        -repository http://download.eclipse.org/releases/oxygen/ \
        -list

**Comment by JESii** [comment]
Output to that command was:
```
org.eclipse.m2e.logback.configuration: The org.eclipse.m2e.logback.configuration bundle was activated before the state location was initialized.  Will retry after the state location is initialized.

Operation completed in 14927 ms.
```

**Comment by ervandew** [comment]
Are you able to start the eclipse gui? When searching for `org.eclipse.m2e.logback.configuration` I see several cases of people having the same issue (totally unrelated to eclim) but with different solutions.

Can you look over some of these results and see if you can get eclipse to successfully list features using the java command from my previous comment?

https://www.google.com/search?q=eclipse%20org.eclipse.m2e.logback.configuration

**Comment by JESii** [comment]
thanks for your help; no longer using eclipse.
