### ISSUE TITLE
eclimd not starting due to : The Security Manager is deprecated and will be removed in a future release

### ISSUE THREAD

**Issue by velocitatem** [ervandew/eclim#620]
After installing eclimd from the official website and running `/usr/lib/eclipse/eclimd` I get the following error:

```
2022-05-29 18:17:08,946 ERROR [org.eclim.eclipse.EclimDaemon] Error starting eclim:
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.lang.System.setSecurityManager(System.java:416) ~[?:?]
	at com.martiansoftware.nailgun.NGServer.run(NGServer.java:388) ~[nailgun-0.7.1.jar:?]
	at org.eclim.eclipse.EclimDaemon.start(EclimDaemon.java:160) [eclim.jar:?]
	at org.eclim.eclipse.EclimStartup$1$1.run(EclimStartup.java:54) [eclim.jar:?]

```

I tried to downgrade to the previous release and the issue persists, maybe I didn't downgrade properly?

**Comment by ervandew** [comment]
What version of java are you running?
