### ISSUE TITLE
eclim not starting

### ISSUE THREAD

**Issue by Taz03** [ervandew/eclim#625]
```
!SESSION 2023-01-27 14:06:41.195 -----------------------------------------------
eclipse.buildId=4.26.0.20221201-1200
java.version=19.0.2
java.vendor=N/A
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  --launcher.suppressErrors -refresh -application org.eclim.application
Command-line arguments:  --launcher.suppressErrors -debug -clean -refresh -application org.eclim.application

!ENTRY ch.qos.logback.classic 1 0 2023-01-27 14:06:43.086
!MESSAGE Activated before the state location was initialized. Retry after the state location is initialized.

!ENTRY org.eclipse.osgi 4 0 2023-01-27 14:06:43.771
!MESSAGE Application error
!STACK 1
org.eclipse.core.runtime.CoreException: Plug-in "org.eclim" was unable to instantiate class "org.eclim.eclipse.EclimApplication".
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.throwException(RegistryStrategyOSGI.java:212)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:206)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:920)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:246)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:63)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:198)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)

```

I followed the eclim installation guide but it is still not working.

**Comment by Taz03** [comment]
```
openjdk version "19.0.2" 2023-01-17
OpenJDK Runtime Environment (build 19.0.2+7)
OpenJDK 64-Bit Server VM (build 19.0.2+7, mixed mode)
JAVA_VERSION=19

/usr/bin/java -Dosgi.requiredJavaVersion=17 -Dosgi.instance.area.default=@user.home/eclipse-workspace -Dosgi.dataAreaRequiresExplicitInit=true -Dorg.eclipse.swt.graphics.Resource.reportNonDisposed=true -Dsun.java.command=Eclipse -Xms256m -Xmx2048m -XX:+UseG1GC -XX:+UseStringDeduplication --add-modules=ALL-SYSTEM -Declipse.p2.max.threads=10 -jar /home/taz/eclipse/java-2022-12/eclipse/plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar --launcher.suppressErrors -debug -clean -refresh -application org.eclim.application
WARNING: Using incubator modules: jdk.incubator.concurrent, jdk.incubator.vector
Install location:
    file:/home/taz/eclipse/java-2022-12/eclipse/
Configuration file:
    file:/home/taz/eclipse/java-2022-12/eclipse/configuration/config.ini loaded
Configuration location:
    file:/home/taz/eclipse/java-2022-12/eclipse/configuration/
Framework located:
    file:/home/taz/eclipse/java-2022-12/eclipse/../../../.p2/pool/plugins/org.eclipse.osgi_3.18.200.v20221116-1324.jar
Loading extension: reference:file:org.eclipse.osgi.compatibility.state_1.2.800.v20221116-1440.jar
	eclipse.properties not found
Framework classpath:
    file:/home/taz/eclipse/java-2022-12/eclipse/../../../.p2/pool/plugins/org.eclipse.osgi_3.18.200.v20221116-1324.jar
    file:/home/taz/.p2/pool/plugins/
    file:/home/taz/eclipse/java-2022-12/eclipse/../../../.p2/pool/plugins/org.eclipse.osgi.compatibility.state_1.2.800.v20221116-1440.jar
Debug options:
    file:/home/taz/eclipse/java-2022-12/eclipse/.options not found
Time to load bundles: 36
Starting application: 2658
An error has occurred. See the log file
```
this is the output of ./eclimd

**Comment by neildsouza** [comment]
Same issue for me
OS: Manjaro Linux

!SESSION 2023-02-25 12:21:27.962 -----------------------------------------------
eclipse.buildId=4.26.0.20221201-1200
java.version=17.0.6
java.vendor=N/A
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  --launcher.suppressErrors -refresh -application org.eclim.application
Command-line arguments:  --launcher.suppressErrors -debug -clean -refresh -application org.eclim.application

!ENTRY ch.qos.logback.classic 1 0 2023-02-25 12:21:29.820
!MESSAGE Activated before the state location was initialized. Retry after the state location is initialized.

!ENTRY org.eclipse.osgi 4 0 2023-02-25 12:21:30.832
!MESSAGE Application error
!STACK 1
org.eclipse.core.runtime.CoreException: Plug-in "org.eclim" was unable to instantiate class "org.eclim.eclipse.EclimApplication".
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.throwException(RegistryStrategyOSGI.java:212)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:206)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:920)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:246)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:63)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:198)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
Caused by: java.lang.ExceptionInInitializerError
	at org.eclim.eclipse.EclimApplication.<clinit>(EclimApplication.java:58)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:204)
	... 16 more
Caused by: java.lang.IllegalStateException: The instance data location has not been specified yet.
	at org.eclipse.core.internal.runtime.InternalPlatform.getLocation(InternalPlatform.java:352)
	at org.eclipse.core.runtime.Platform.getLocation(Platform.java:699)
	at org.eclim.logging.Logger.<clinit>(Logger.java:28)
	... 23 more
